cryostatio/cryostat-web

- src/app/connect/connect-button.component.ts
Here is the front-end side of the command name change in https://github.com/rh-jmc-team/container-jfr/pull/2. Seems to work fine when deployed. Let me know if I missed something.
> Rename 'port-scan' command to 'scan-targets'

- src/app/recording-list/archived/archived-recording-list.component.ts
Current recording list is always present, so archived list's
upload-recording handler is redundant and causes duplicate handling of
the response message
Fixes #17
> Remove upload-recording onResponse from archived list

- README.md
> Remove reference to trello board. Format name similarly to rh-jmc-team/container-jfr

- package-lock.json
- package.json
- src/app/command-channel.service.ts
- src/app/recording-list/current/current-recording-list.component.ts
Most of the time, container-jfr-web doesn't need to care about message IDs,
since each incoming message is either disregarded in general, or contains
useful information about a container-jfr side (or remote JVM side) state
change, which the UI should track regardless of which client initiated the
action resulting in this state change.
There are two UI-specific cases where this can and should be avoided:
- when displaying a notification after saving a recording to storage
- when opening a Grafana tab after uploading a recording
This PR uses message ID tracking to correct the behaviour so that these
notifications and tabs are only displayed/opened when the response
corresponds to an action that the user of this client instance
initiated.
> Use message IDs to prevent spurious notifications

- src/app/Dashboard/Dashboard.tsx
- src/app/RecordingList/RecordingList.tsx
- src/app/Shared/Services/CommandChannel.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/app/TargetView/TargetView.tsx
- src/app/routes.tsx
This PR modifies the TargetSelect component so that it can be reused, reinstates the Dashboard main page component containing a TargetSelect, and adds a TargetSelect to the RecordingList. The intent is to allow users to quickly switch targets while remaining on the same content view, without needing to click back and forth between the previous standalone target selection view.
> Add TargetSelect widget on RecordingList

- LICENSE
We should find some tool to automate adding license headers to source files, but in the meantime let's add a license to the repository.
> Add UPL license file

- src/app/AppLayout/AppLayout.tsx
- src/app/BreadcrumbPage/BreadcrumbPage.tsx
- src/app/CreateRecording/CreateRecording.tsx
- src/app/Notifications/NotificationCenter.tsx
- src/app/Notifications/Notifications.tsx
- src/app/RecordingList/RecordingList.tsx
- src/app/Shared/Services/CommandChannel.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/TargetView/TargetView.tsx
- src/app/routes.tsx
This PR adds an initial pass at #58 and an associated minor enhancement to #57 .
A new "Create Recording" view is added, which is routed as a child of the Recordings List view. The Recordings List gains a
"Create" toolbar button which links to the new view.
The new view is just a form with a bit of logic to determine what command name and arguments to use for the recording
request sent to ContainerJFR. When the request is successfully submitted, the view routes back to the Recordings List.
If the user cancels out of the view then they are returned to their previous location - currently this can only be the
Recordings List, but other links are possible in the future.
Not yet handled:
~~1. input validation~~
~~2. any system for notifying users of what went wrong if the request fails …
> "Create Recording" view

- src/app/RecordingList/RecordingList.tsx
This is based on top of #59
Mockup: https://projects.invisionapp.com/d/main#/console/19772434/413969810/preview
This PR reimplements the Recording List as a Patternfly Data List, rather than as a Table. This allows more flexibility in the rendering of the cells - for example, the download and report URLs are now clickable links.
This also opens the door to more advanced custom styling options, such as making the rows expandable and containing more custom rendered elements (as opposed to an expandable table, which can only contain plain text). This could include copying the ContainerJFR Web Angular UI where the expanded rows contain an inline recording report. The Data List also allows for action buttons and other customized elements to be placed within the cells, which will likely be used …
> Recording List overhaul as Data List

- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Events/Events.tsx
- src/app/routes.tsx
This PR adds an initial pass at the Events views outlined in #55 and #56 .
The Templates view is missing the ability to select rows and create recordings from these templates, since the view for creating recordings in general is not yet implemented (see #59).
~~The Types view needs to be made scrollable or to gain pagination, since the number of events is quite long and currently they are all rendered into an extremely large table.~~
Fixes #55 
Fixes #56
> Initial Events view

- webpack.prod.js
Fixes an issue where invalid prod mode source maps cause browsers to be
unable to open the client when built in prod mode.
See https://github.com/webpack/webpack/issues/8302
> Use eval-source-map in prod mode

- src/app/CreateRecording/CreateRecording.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/SnapshotRecordingForm.tsx
Fixes #58
Based on top of #66
This PR puts the existing recording creation form into a tab within its card and adds a second tab which contains a simple "form" explaining what JFR Snapshots are and allowing the user to create a Snapshot by clicking the "Create" button.
Also, the two tabbed form components are not unmounted when not visible, so the "custom recording" form state will be preserved if the user switches between custom and snapshot tabs.
> Add ability to create Snapshot recordings

- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/RecordingList/ArchivedRecordingsList.tsx
- src/app/RecordingList/RecordingList.tsx
- src/app/RecordingList/RecordingsDataTable.tsx
Adds a conditionally-displayed Archived Recordings tab to the Recordings List card component. If the ContainerJFR instance does not support recording archiving then the UI is unchanged - no tabs are displayed on the card, only the Active Recordings table. If Archives are supported then the active recording list gains an Archive button, and the new view allows a list of archived recordings to be seen, downloaded, and deleted, as well as reports viewed by link URL.
> Add "Archived Recordings" view tab

- src/app/CreateRecording/CreateRecording.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Events/Events.tsx
This adds an action button menu to each row of the Event Templates view, currently containing a single action button. When clicked this action button routes the user to the Create Recording form view, with the template/eventSpecifier fields of the form pre-filled and validated according to the event template that the user chose on the previous view.
> Add action button for creating recordings from template

- src/app/RecordingList/ArchivedRecordingsList.tsx
- src/app/Shared/Services/CommandChannel.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
Rebased and reopened version of #80, after `react` branch merge to `master`.
The goal here is simply to patch the React client to work with ContainerJFR's upcoming non-connection-oriented/connectionless API changes ( https://github.com/rh-jmc-team/container-jfr/pull/161 ). It is intentionally minimal and provides support for the backend changes only, not changing any client layout or behaviour.
The `CommandChannel` front-end "service" object gains an RxJS Subject which maintains a piece of state representing the "connected" target JVM, emulating the previous stateful connection-oriented API. This is just to maintain compatibility with the rest of the structure of the React client and will be removed at a later time, so that the web application itself also works in a "connectionless" …
> Connectionless API

- src/app/TargetSelect/TargetSelect.tsx
This simply adds a button to the Target Select component card's action area, which sends a scan-targets command when clicked. The button and the selection dropdown are disabled in between the message being sent and a response received. The selection dropdown is reactively updated as usual when a response is received.
> Add target list refresh button

- src/app/Shared/Services/CommandChannel.service.tsx
The periodic ping was initially used for development testing to check
whether communication errors were due to closed connections or the
backend not responding, but this is no longer a common concern and so
the ping serves no practical purpose. It should be removed to prevent it
from clogging backend logs.
> Remove timed background command channel ping

- src/app/AppLayout/AppLayout.tsx
When the window is resized to a vertical view (narrow width) the sidebar starts covering the page (overlay), and when a page on the menu is chosen the bar now closes automatically (given nothing can be done with the bar open).
> enable sidebar to autohide on narrow screen

- src/app/Shared/Services/CommandChannel.service.tsx
Request health endpoint to determine if the Grafana configuration is set up, and only if it is then request URLs. Unified error message when configuration is not present.
> Call health endpoint

- src/app/RecordingList/ActiveRecordingsList.tsx
Fixes #86.
I guess something worth noting is that before, the web client would append `/load` to the datasource URL env var, but now, the command just uses the env var directly. So a previous env var of `http://localhost:8080` should be changed to `http://localhost:8080/load`.
> Support Backend Changes to `upload-recording` that Assumes Datasource URL

- src/app/AppLayout/AppLayout.tsx
- src/app/CreateRecording/CreateRecording.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/SnapshotRecordingForm.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Login/Login.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/RecordingList/ArchivedRecordingsList.tsx
- src/app/RecordingList/RecordingList.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/CommandChannel.service.tsx
- src/app/Shared/Services/Report.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/Shared/Services/Target.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/app/TargetView/TargetView.tsx
- src/app/utils/useSubscriptions.ts
See rh-jmc-team/container-jfr#222
This PR replaces all uses of the command channel with HTTP calls instead, in preparation for support for RJMX authentication (rh-jmc-team/container-jfr#225) to come later.
> Replace Command Channel usage with HTTP REST APIs

- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/RecordingList/ArchivedRecordingsList.tsx
- src/app/Shared/Services/Api.service.tsx
A previous commit refactored the ApiService in a way that caused all
upload requests to use the HTTP API path as if they were all active
recordings. This re-adds a differentiation in the service implementation
between archived and active recordings to reflect the different HTTP API
paths for uploading either to a jfr-datasource.
Fixes #119
> Fix bug preventing archived recording uploads

- src/app/AppLayout/AppLayout.tsx
- src/app/AppLayout/AuthModal.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Report.service.tsx
- src/app/Shared/Services/Target.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/app/TargetView/TargetView.tsx
Fixes #117
Based on top of #110
> JMX Auth UX

- src/app/CreateRecording/CustomRecordingForm.tsx
There could be situations where a recording option becomes disabled but its value is still sent. This only sends the relevant recording options in the new recording request.
> Only send recording options that are relevant (not disabled)

- src/app/CreateRecording/SnapshotRecordingForm.tsx
Fixes #124, It seems that the button layout is vertical when creating custom flight recording because it is a horizontal form. By making the snapshot recording horizontal as well at least it makes both button layouts uniform (both are now stacked).
> unify button layout when creating new recordings

- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/RecordingList/ArchivedRecordingsList.tsx
- src/app/RecordingList/RecordingsDataTable.tsx
Fixes #133. Currently the loading spinner is visible while waiting for the user to input the JMX auth credentials. However, in the case of a connection failure (for example when cjfr does not have the cert file for the target in smoketest) the loading spinner just stays there forever. I think ideally an error message or icon should replace it, but doing so might require more changes to the Api.service.
> Create loading state in recording list views

- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
Fixes #150 
I don't know if this is the optimal way to solve this, I could not think of any other way because handleError in Api.service.tsx doesn't throw an error, it retries. Therefore, the api call never gets back to the caller with an error, and was showing the loading screen.
> When auth failure occurs display errorView

- src/app/RecordingList/ReportFrame.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Report.service.tsx
Do not expect response status message to contain additional details, rather these additional details are written in the response body
See also rh-jmc-team/container-jfr#322
> Use error response body as error detail message

- webpack.common.js
- webpack.dev.js
- webpack.prod.js
Adds configuration to split app.bundle.js so that the main app.bundle.js
contains generally only container-jfr-web assets, and dependencies
(node_modules) are split out into separate bundle files. The
app.bundle.js for production builds also gains a content hash part of
its filename (as do all vendored dependency bundles) to help ensure that
assets are not incorrectly cached by browsers or webservers.
This allows the client web browser to only download the portions of the
web-client that have changed when (re)visiting the application, reducing
load times. This also allows for better cache handling since
infrequently-updated dependencies do not need to be re-downloaded every
time the application is rebuilt.
Fixes #149
> Configure webpack bundle splitting

- package.json
- src/app/Events/EventTypes.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/RecordingList/RecordingList.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/app/routes.tsx
- yarn.lock
Fixes #162
This heavily refactors, simplifies, and renames the `CommandChannel` to the `NotificationsChannel`, with some of the old functionality moved to the `ApiService`.
The new `NotificationsChannel` allows consumer components to subscribe to notifications sent by the ContainerJFR backend and respond in various ways. Two such consumers are included: the first is the `NotificationsChannel` itself, which displays a notification message box when `WS_CLIENT_ACTIVITY` notification messages are received (when a WebSocket client (dis) connects). The second is the `TargetSelect` component, which now listens for `TargetJvmDiscovery` notifications, which are emitted by the backend when async target discovery observes a new target appearing or an old target disappearing. The `TargetSelect` …
> Support Notifications Channel

- package.json
- webpack.prod.js
- yarn.lock
Skip building if sources and dependencies are unchanged
This substantially speeds up clean rebuilds (from ~11s to ~700ms in my tests just now), which are often encountered when container-jfr-web is built as a submodule of ContainerJFR itself before packaging into an OCI container. This can be tested by simply running `yarn run build` repeatedly.
> Apply only-if-changed plugin to 'prod' builds

- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
TargetViews are hidden when the target selection is cleared, so there is no need to attempt to update the contents. Furthermore, updating the contents with a cleared target results in a 404 response, since the request will be sent with an empty string for a targetId.
Fixes #170
> Do not refresh views when target selection cleared

- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
TargetViews are hidden when the target selection is cleared, so there is no need to attempt to update the contents. Furthermore, updating the contents with a cleared target results in a 404 response, since the request will be sent with an empty string for a targetId.
Fixes #170
Direct backport of #171
> [v1] Do not refresh views when target selection cleared

- src/app/RecordingList/ActiveRecordingsList.tsx
Hi,
This PR addresses https://github.com/cryostatio/cryostat-web/issues/165 , adding notification handlers for each of the new notifications emitted by the backend on the Notifications channel. Whenever the web client receives one of these it will trigger a refresh of the recordings list to reflect new recordings being created/deleted/archived in the backend.
> Add Handlers to refresh recording list when notifications are received

- src/app/Shared/Services/Api.service.tsx
`.jfc` is used as the file extension for flight recorder event templates by the JDK as well as by JMC, so it makes sense to use the same extension when we download and save templates.
> Download templates as .jfc, not .xml

- src/app/TargetSelect/TargetSelect.tsx
Cryostat backend never emits the 'CHANGED' event type anymore, instead emitting a LOST-FOUND sequence in any scenario where a target modification is detected
Related to https://github.com/cryostatio/cryostat/issues/388
> Remove handling for 'CHANGED' discovery event

- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/utils/useSubscriptions.ts
> ActiveRecordingsList hang fix

- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Target.service.tsx
- src/app/TargetSelect/CreateTargetModal.tsx
- src/app/TargetSelect/TargetSelect.tsx
> Custom targets

- src/app/CreateRecording/CreateRecording.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
See cryostatio/cryostat#486
This removes the text area on the Custom Recording creation form, corresponding to the backend change that has removed support for the old event specifier string syntax, which has been superceded by custom templates.
This also enhances the template selection dropdown on the form to organize the templates into TARGET/CUSTOM sections. Previously, all template names were listed together in one group. The indication of TARGET/CUSTOM type was included in the text area when a template was selected.
For testing convenience, this PR includes a commit reverting #214, due to #216. This change is not actually part of this PR. Once this change has been looked over and provisionally approved I will rebase and remove that first commit before merging.
> Remove event specifier string text area

- src/app/Shared/Services/NotificationChannel.service.tsx
Rename the channel path to correspond with changes in the back-end (cryostatio/cryostat#537), which better reflect its updated usage as a one-way notifications channel instead of an interactive command client. 
Fixes #230
> Rename websocket notifications channel path

- yarn.lock
Bumping css-what from 5.0.0 to 5.0.1 to fix CVE-2021-33587.
> build(deps): update css-what to 5.0.1

- src/app/AppLayout/AppLayout.tsx
- src/app/Shared/Services/Api.service.tsx
Fixes #77
This adds the Help ('?') icon in the page header. Clicking this button reveals the About modal, as seen in the screenshot.
> feat(applayout): add help icon and about modal

- src/app/AppLayout/AppLayout.tsx
- src/app/routes.tsx
> fix(settings): move from vert nav to masthead tool

- src/app/Login/Login.tsx
> feat(login): display notification on bad credentials

- src/app/CreateRecording/CustomRecordingForm.tsx
Related to #252
Removes a console.log added in a previous PR and mistakenly not removed
> chore(recordings): remove console.log

- src/app/AppLayout/AppLayout.tsx
This makes the Cryostat version string a clickable link which brings the user to the GitHub repository for cryostatio/cryostat as of the commit reference, and also enhances the "Bug Reports" item to have a "Known Issues" (link to issues list) and a "File a Report" item (creates a partially filled new issue).
Fixes #270
> feat(about): enhance version string and bug tracker

- src/app/Notifications/NotificationCenter.tsx
- src/app/Notifications/Notifications.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/Shared/Services/Targets.service.tsx
- src/app/TargetView/TargetView.tsx
- src/app/routes.tsx
Fixes #268
Groups notifications into three categories: "Completed Actions", "Network Info", and "Problems". 
Notifications confirming a user's action has succeeded will appear in "Completed Actions". "Network Info" contains any messages related to JVM target discovery and WebSocket disconnection. All warning and error notifications appear in the "Problems" category.
When opening the drawer, "Completed Actions" is expanded by default. If there are unread errors, the "Problems" tab is expanded instead. Only one category can be expanded at once.
> feat(notifications): Sort notifications by category

- src/app/Notifications/NotificationCenter.tsx
- src/app/Notifications/Notifications.tsx
- src/app/RecordingList/ActiveRecordingsList.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/Shared/Services/Targets.service.tsx
Fixes #284 
Only one notification should appear when recordings are created. All notifications indicating that a user's action was successfully processed now display the green "success" message style.
>  the subscription to this notification category should be somewhere long-lived
The NotificationChannel now subscribes to all WebSocket messages related to updating recording state (ie recording created/archived/saved/deleted) so that these notifications are displayed even if users navigate away from the Recordings page.
> fix(notifications): Fix inconsistent action notification categories

- src/app/AppLayout/AppLayout.tsx
- src/app/Notifications/Notifications.tsx
Fixes #267 
Since the purpose of adding toast notifications is to confirm a user’s action was processed successfully and Patternfly recommends that all of those notifications should have the “success” message variant, I decided to change all “user action confirmed” notifications to use the “success” variant in #288. 
Then the alert group would just need to filter and display messages that have either error, warning, or success variants. 
Adding a default 8-second timeout also seemed appropriate since toasts will appear after completing user actions. Any unread errors will still appear in the notifications drawer.
> feat(notifications): Show toast on user action success

- src/app/TargetSelect/TargetSelect.tsx
Fixes #278
> This is overall a stopgap measure to enhance the current state management and routing. The better solution is outlined in #78 - the target selection should be included in the view route.
> feat(targets): Persist selected target in localStorage

- src/app/About/About.tsx
- src/app/About/AboutCryostatModal.tsx
- src/app/About/AboutDescription.tsx
- src/app/AppLayout/AboutCryostatModal.tsx
- src/app/AppLayout/AppLayout.tsx
- src/app/NotFound/NotFound.tsx
- src/app/routes.tsx
Fixes #266.
Would appreciate some suggestions to improve this design since my current approach causes the bug listed below.
1) In addition to the existing masthead help icon, clicking the "About" nav link on the PageSideBar will display the AboutModal. Unlike the other nav links, users can view the AboutModal by clicking the nav link without logging in.
2) The url http://localhost:9000/about allows users to view/copy a link to the AboutModal. Followed this example to create the modal route: https://reactrouter.com/web/example/modal-gallery
Note: The example only displays their modal when the route matches “/img/:id”. Since I wanted to display the modal on top of any page, the `RouteWithTitleUpdates``path` prop is set to `location.pathname`
Bug: if you open a new tab and enter …
> feat(about): View About info from PageSideBar

- src/app/Login/Login.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/routes.tsx
Fixes #300
Detect WebSocket connection rejection reason status code. If the code indicates that the connection was rejected/closed because the authenticating user has insufficient permissions, do not attempt automatic reconnections.
This should fix the looping problem described in cryostatio/cryostat#687 , where a full OpenShift reduced-permissions user account is set up. A possibly easier test case is to run this web-client using the typical devserver setup against a Cryostat smoketest.sh, but where the Cryostat image has been modified to reject WebSocket subprotocol authentication. I have prepared one such image that can be used like:
```
CRYOSTAT_IMAGE=quay.io/andrewazores/cryostat:fail-ws-subproto CRYOSTAT_AUTH_MANAGER=io.cryostat.net.BasicAuthManager …
```
> fix(login): do not re-attempt ws connection on auth fail

- src/app/Notifications/Notifications.tsx
Fixes #304
The root cause of the bug is that services and components may attempt to display a notification with an Error object as the message to display to the user. This fails because the rendered child component (content of the graphical notification) must be a string. This is a bit tricky because the Notification data type specifies that the message property should be a string, however many/most places where an Error object may be obtained it is typed as 'any', which breaks some of the TS compiler's type-checking guarantees at compile time. To work around this, I apply a simple fix to the notifications service: do a runtime check of the message type, and if it isn't an actual string, apply "JSON.stringify" to serialize it to a string before it is displayed.
> fix(notifications): handle Error type messages

- src/app/TargetSelect/TargetSelect.tsx
Fixes #312 
When a previously selected target disappears, the TargetSelect component will display `Select a target` instead of the disconnected target. As before, `localStorage` is updated whenever the user selects a new target.
> fix(targets): Deselect nonexistent target

- src/app/AppLayout/AppLayout.tsx
- src/app/routes.tsx
Fixes #302
Since there are only 5 menu items, I decided to place the menu items under section headers without collapsing them.
https://www.patternfly.org/v4/components/navigation/design-guidelines
> feat(AppLayout): Group related menu links together

- src/app/Recordings/ArchiveUploadModal.tsx
- src/app/Recordings/CancelUploadModal.tsx
- src/app/Shared/Services/Api.service.tsx
Fixes #331
Fixes #332
Displays a React dialog prompt when the user clicks the Cancel button during an active upload, and displays the browser's native prompt to confirm when the user tries to refresh or close the tab/window. Also uses an AbortController/AbortSignal to actually instruct the browser to stop the file upload request if the user does confirm they wish to cancel the upload.
To test, it's probably best to use the browser devtools' simulated request throttling during the upload, so that there is a reasonable human amount of reaction time to cancel the upload before it completes. If testing in podman the upload is likely to complete very quickly for small-ish JFR files otherwise. After cancelling the request, the devtools' Network tab should show that the request was stopped with …
> fix(archiveuploads): display prompt on cancel or navigation

- src/app/Shared/Services/NotificationChannel.service.tsx
> fix(notifications): Do not show temporary reconnection errors

- src/app/Shared/Services/Api.service.tsx
> chore(ApiService): Ensure all API requests return a useable boolean where it makes sense

- src/app/TargetSelect/CreateTargetModal.tsx
Fixes #347 
The accepted JMX service url format is now indicated in the helper text below the form input. I decided to use helper text instead of pre-filling the field with a default value to avoid the need for users to delete the default value before pasting their own url.
> feat(targets): Add example JMX service url

- src/app/TargetSelect/CreateTargetModal.tsx
Fixes #348 
The create button is disabled until a user enters text into the Connect URL field. If the submission is non-empty and invalid, clicking `Create` will display more helper text instead of posting a request.
> fix(targets): Validate connectUrl before submission

- src/app/AppLayout/AppLayout.tsx
- src/app/Login/OpenShiftPlaceholderAuthForm.tsx
- src/app/Shared/Services/Login.service.tsx
Related https://github.com/cryostatio/cryostat/issues/717
In order to log out of the OAuth server, the frontend needs to make a POST request to the OAuth server's `/logout` endpoint, which removes the session cookie stored in the OAuth server. The backend will delete the access token and return the `/logout` url. Note that deleting the access token without removing the session cookie will cause the OAuth server to immediately login a user after logging out.
[OpenShift OAuth logout docs](https://docs.openshift.com/container-platform/4.9/authentication/managing-oauth-access-tokens.html#oauth-delete-tokens_managing-oauth-access-tokens)
[OpenShift OAuth endpoint for deleting access tokens](https://docs.openshift.com/container-platform/4.9/rest_api/oauth_apis/oauthaccesstoken-oauth-openshift-io …
> feat(auth): Add OAuth logout

- src/app/Shared/Services/NotificationChannel.service.tsx
Related to #349
This refactors the explicit notification handling in the `NotificationChannel`, extracting out some configuration objects into a `Map` to redefine the existing notifications handling for things like WebSocket client activity, or recording start/stop/archive/delete actions.
This is then further extended by adding handling for notifications that have a category not specified in the above configuration map. The client will still attempt to display these notifications, but the display will include the raw message category from the WebSocket notification message, and the notification body will simply be the body field of the notification message, without any further contextual information, and likely with JSON formatting tokens present. This is just a catch-all handler in case …
> feat(notifications): service handles and displays all incoming WS messages

- src/app/Shared/Services/NotificationChannel.service.tsx
Fixes #349
Since #367 a notification is already shown when uploading or deleting event templates, but this PR adds a specific handler so that the notification is displayed with a nicely formatted title and message.
> fix(notifications): add template notification handling

- src/app/Rules/Rules.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/routes.tsx
Fixes #375
Depends on https://github.com/cryostatio/cryostat/pull/837
> feat(rules): add UI for displaying automated rules

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Rules/CreateRule.tsx
- src/app/Rules/Rules.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/TemplateSelector/FormSelectTemplateSelector.tsx
- src/app/TemplateSelector/TemplateSelector.tsx
- src/app/routes.tsx
Fixes #377
For CORS/devserver testing you may need to use https://github.com/cryostatio/cryostat/pull/838 on the backend.
> feat(rules): add rule creation form and deletion action

- src/app/Dashboard/Dashboard.tsx
- src/app/Rules/CreateRule.tsx
- src/app/Rules/MatchExpressionEvaluator.tsx
- src/app/Rules/TargetJson.tsx
- src/app/Shared/Services/Target.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/app/TargetView/TargetView.tsx
> feat(rules): add match expression evaluation component to rule creation form

- src/app/Settings/AutoRefresh.tsx
- src/app/Settings/Settings.tsx
- src/app/Settings/WebSocketDebounce.tsx
Related to #343
This is a refactor preparing for adding more settings to this view. There are minor visual changes with text styling but otherwise this is just a code maintenance item.
> chore(settings): refactor for dynamic settings cards

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/EditRecordingLabels.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/RecordingActions.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
Related https://github.com/cryostatio/cryostat/issues/709
When creating recordings, users can add their own metadata with key-value label pairs. You can also edit labels for all active and archived recordings.
The labels are stored in the filesystem for now until we find a solution to manage the metadata when Cryostat is restarted (see https://github.com/cryostatio/cryostat/issues/709#issuecomment-1035314270)
> feat(recordings): Add metadata recording labels

- src/app/AppLayout/AppLayout.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Notifications/Notifications.tsx
- src/app/Settings/AutoRefresh.tsx
- src/app/Settings/NotificationControl.tsx
- src/app/Settings/Settings.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/Shared/Services/Settings.service.tsx
- src/app/Shared/Services/Targets.service.tsx
> feat(settings): user can enable/disable notifications by category

- src/app/AppLayout/AuthModal.tsx
- src/app/AppLayout/JmxAuthForm.tsx
- src/app/SecurityPanel/CreateJmxCredentialModal.tsx
- src/app/SecurityPanel/ImportCertificate.tsx
- src/app/SecurityPanel/SecurityPanel.tsx
- src/app/SecurityPanel/StoreJmxCredentials.tsx
- src/app/SecurityPanel/TargetCredentialsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
Fixes #388 
Adds a table listing targets with stored credentials in the Security tab. Also refactors the Security panel to make it easier to add more cards in the future.
> feat(credentials): Manage target JMX credentials

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
Related to https://github.com/cryostatio/cryostat/pull/864
> fix(notifications): handle labels nested within metadata

- src/app/CreateRecording/EditRecordingLabels.tsx
Related https://github.com/cryostatio/cryostat/issues/865
> fix(recordings): disallow whitespace in labels

- src/app/Shared/Services/Api.service.tsx
Fixes #390 
When two headers objects are passed to `fromFetch`, the last header object listed (`config.headers`) seems to replace the previous `headers` object (`login.getHeaders`). This appends the correct `Content-type`, but removes the `Authorization` header from the request. Appending the `config.headers` into the original `headers` object, then passing in the updated `headers` object last will preserve all the headers.
> fix(rules): fix header concatenation

- src/app/Shared/Services/Api.service.tsx
Fixes #399 
- passing request headers as a `Headers` object in the `RequestInit config` lets the `customizer` find the correct headers object
- fix header iteration loop
- fix code formatting
> fix(api): include Authorization header for all requests

- src/app/SecurityPanel/StoreJmxCredentials.tsx
Fixes #403 
When credentials were added or deleted, both `refreshStoredTargetsList` and the notification subscriptions attempted to update the `storedTargets` list at the same time. When an item was deleted, the resulting `storedTargets` list became empty.
`refreshStoredTargetsList` should only be called on page refresh. Only notification subscriptions will update the table from now on. I also removed the state variable `isEmpty` and simply checked for `storedTargets.length === 0`.
Planning to add unit tests for this component in a separate PR.
> fix(jmx): populate credentials table via notification only

- src/app/Events/EventTemplates.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Rules/Rules.tsx
- src/app/SecurityPanel/StoreJmxCredentials.tsx
Fixes #411
- fix(security): jmx credentials view displays loading spinner
- fix(recordings): table toolbars remain visible while loading
- fix(rules): display loading spinner
- fix(templates): table toolbar remains visible while loading
> fix(loading): ensure loading spinners are displayed

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
Fixes #409 - the `target.target()` Observable in `postTargetRecordingMetadata` seemed to be firing twice.
I also noticed the metadata labels notification subscription didn't check if the notification applied to the selected target. Added a check to prevent unnecessary computation when receiving metadata label notifications.
This fix prevents an error toast from popping up but leaves the state otherwise unchanged. Up to you if you want to backport it.
> fix(labels): Prevent duplicate labels POST call

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
> fix(snapshots): remove successful snapshot creation notification handling

- src/app/Shared/Services/Api.service.tsx
Related to https://github.com/cryostatio/cryostat/issues/970
> chore(api): graphql is now in API v2.2, not beta

- src/app/BreadcrumbPage/BreadcrumbPage.tsx
Fixes #459 
Fixes view refresh taking a long time when following breadcrumbs.
> fix(navigation): fix unncessary page refresh when following breadcrumbs

- src/app/BreadcrumbPage/BreadcrumbPage.tsx
Related to #459 
Previous fix didn't remove `to` property in `BreadcrumbItem`. There seems to be no effect if not removing but it might not be clear which behaviour the breadcrumb follows as we also have  `<Link>`'s `to` property.
> chore(navigation): remove breadcrumb href since replaced by Link

- .github/workflows/ci.yaml
- .github/workflows/submodule.yaml
Example workflow run in my fork: https://github.com/ebaron/cryostat-web/actions/runs/2516537219
Example commit from my fork: https://github.com/ebaron/cryostat/commit/d7b51f7cce732440776841603307a0cf9ba8cc22
Fixes: #469
> ci(submodule): push update to parent submodule

- src/app/Archives/AllArchivedRecordingsTable.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Modal/DeleteWarningModal.tsx
- src/app/Modal/DeleteWarningTypes.tsx
- src/app/Modal/DeleteWarningUtils.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/DeleteWarningModal.tsx
- src/app/Rules/RuleDeleteWarningModal.tsx
- src/app/Rules/Rules.tsx
- src/app/SecurityPanel/StoreJmxCredentials.tsx
- src/app/Settings/DeletionDialogControl.tsx
- src/app/Settings/NotificationControl.tsx
- src/app/Settings/Settings.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Settings.service.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/__snapshots__/EventTemplates.test.tsx.snap
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Rules/Rules.test.tsx
- src/test/SecurityPanel/StoreJmxCredentials.test.tsx
Fixes #462 
Also fixes #382
I didn't add a task or mention to add a prompt for deleting rules yet because I wanted to take it steady with React. If anyone thinks it should be included in this PR and the associated issue, please feel free. 
Any feedback and thoughts on what I've done?
> feat(ui): add deletion prompt when deleting an active or archived recording

- src/app/Rules/CreateRule.tsx
- src/app/Rules/Rules.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/Rules/Rules.test.tsx
- src/test/Rules/__snapshots__/CreateRule.test.tsx.snap
Related to https://github.com/cryostatio/cryostat/issues/1014
As usual, this needs to be tested along with the corresponding backend support in https://github.com/cryostatio/cryostat/pull/1015 . For submodule/CI reasons the "depends on" relationship is inverted.
Adds support for the new "initial delay" parameter for automated rule definitions.
Previously, rules only had an "archival period". So when a rule was created with period *t* - or when a new matching target appeared - at time *x* archived recordings would be copied at time *x+t*, *x+2t*, *x+3t*, ... , *x+nt*.
Now, rules can be created with both an archival period and an initial delay. If the rule is created or a target appears at time *x*, and the rule has archival period *t* and initial delay *d*, then archived recordings are …
> feat(rules): implement initialDelay

- src/app/Events/EventTemplates.tsx
Fixes #472
The only thing that I'm thinking is if it's better to test every field of a `Template` object instead of just filtering `name` and `type`
i.e. `if (o.name != v.message.template.name) || type != type || provider != provider || description != description ` or make some helper for that.
I'm thinking not, since users can only create `CUSTOM` templates for now and cannot create new custom event templates with the same name, because of this `Event template "Continuous" already exists caused by MutableTemplateService.InvalidEventTemplateException: Event template "Continuous" already exists`
> fix(templates): delete custom event template no longer deletes default templates with similar name

- src/app/Rules/CreateRule.tsx
- src/test/Rules/__snapshots__/CreateRule.test.tsx.snap
Fixes #433 
It works but if a user clicks on a certain target and if there's any errors with SSL authentication or JMX authentication `e.g. HTTP 427: JMX Authentication Failure`, the `ServiceApi` will stop working and get stuck on the error, and hence subsequent clicks on the dropdown targets won't do anything 
I'm not sure why I even get these errors since I'm running 
```
CRYOSTAT_DISABLE_SSL=true CRYOSTAT_DISABLE_JMX_AUTH=true CRYOSTAT_CORS_ORIGIN=http://localhost:9000 sh smoketest.sh
```
> fix(rules): automated rule creation now list eventTemplates based on target selector

- src/app/CreateRecording/CustomRecordingForm.tsx
Fixes #402
Thoughts or anything I missed? 
One thing I was wondering about was that, if users put 0 in the `Duration` input, the recording will be set to `Continuous` and I'm wondering if there's any indication that that is the case on the UI somewhere, and if not, if that should be included as well.
> feat(recording): include helperText for invalid recording names when creating new recordings with form

- src/app/Shared/MatchExpressionEvaluator.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/test/Rules/CreateRule.test.tsx
Related to https://github.com/cryostatio/cryostat-web/issues/294#issuecomment-1204281360
Depends on https://github.com/cryostatio/cryostat/pull/1037
Fixes #294
The fix stops the `TargetSelect` from selecting a target if it was selected when a `TargetJvmDiscovery` LOST notification is emitted. So it is entirely dependent on LOST notifications getting through somewhat quickly.
> fix(targets): select TargetSelect to none when TargetJvmNotification LOST if that target is currently selected

- src/app/TargetSelect/TargetSelect.tsx
- src/test/Rules/__snapshots__/CreateRule.test.tsx.snap
- src/test/Targets/TargetSelect.test.tsx
> fix(targets): disable delete button on non-custom targets

- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/RecordingMetadata.tsx/BulkEditLabels.test.tsx
Fixes #442 
Uses the backend fix from https://github.com/cryostatio/cryostat/pull/971 to modify and retrieve archived recording labels saved from a specified target. 
I'll add another follow-up PR to apply the same fix to the all-archives view once Hareet merges his.
> fix(labels): edit labels for distinct recordings with identical file names

- src/app/app.css
override some Patternfly styling update that broke this view
Fixes #514
> fix(about): correct logo height using \!important override

- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Related to https://github.com/cryostatio/cryostat/pull/1077
Related to https://github.com/cryostatio/cryostat/issues/964
- fix(archive): correct nested data structure for GraphQL archive queries
- apply whitespace trim fixes
> fix(archive): correct nested data structure for GraphQL archive queries

- src/app/utils/useSubscriptions.ts
Fixes #528 
Cleaned up useSubscriptions hook to remove local states and reduce re-rendering.
> chore(hooks): update useSubscriptions to reduce re-rendering

- src/test/Recordings/Filters/DateTimePicker.test.tsx
Fixes #530 
Properly set up Jest mock system timer and added callback to reset to mock date to real after `DatetimePicker` tests.
The issue is that `DateTimePicker` should be imported after systemtime mock to receive the mocks.
> fix(jest): fix mock systemtime setup

- src/app/Rules/CreateRule.tsx
- src/app/Rules/Rules.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/Rules/Rules.test.tsx
- src/test/Rules/__snapshots__/CreateRule.test.tsx.snap
> feat(rules): rules can be enabled/disabled

- src/app/TargetSelect/TargetSelect.tsx
- src/app/TargetView/TargetView.tsx
- src/test/Dashboard/Dashboard.test.tsx
- src/test/Dashboard/__snapshots__/Dashboard.test.tsx.snap
- src/test/Targets/TargetSelect.test.tsx
- src/test/Targets/__snapshots__/TargetSelect.test.tsx.snap
Fixes #504 
Reworded helper texts and target-select placeholders. Added some tests for empty states in dashboard.
> fix(target): reword helper texts

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Shared/Services/Api.service.tsx
> feat(recording): add form control for archiveOnStop

- src/app/AppLayout/AppLayout.tsx
- src/app/ErrorView/ErrorView.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Rules/CreateRule.tsx
- src/test/Recordings/RecordingsTable.test.tsx
- src/test/Rules/CreateRule.test.tsx
Fixes #527 
Fixes #485 
Depends on https://github.com/cryostatio/cryostat/issues/1104
**Fixes**
- Added Auth form or SSL warning if failing to retrieve a template list from selected target.
- Editted ErrorView for better layout and visuals :D
**Chore**
- Use `useSubscriptions` for subs and `React.useCallback` for callbacks in `AppLayout`.
> fix(rules): show error view and modal when template retrieving fails

- src/app/ErrorView/ErrorView.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/Recordings.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Rules/CreateRule.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/Rules/__snapshots__/CreateRule.test.tsx.snap
- src/test/Targets/TargetSelect.test.tsx
- src/test/Targets/__snapshots__/TargetSelect.test.tsx.snap
Fixes #485
Related to #540 
The issue is that the observable for `427` error code is hanged waiting for retry.
So, I added a `Retry` button for auth failure, which picks up the hanged `Observable` to retry. If the user does not click cancel, it will still be there until moving away to another page or reloads.
Also, just noticed the total size for archived recording is displayed when there are no recordings. This is removed now.
> feat(auth): add retry button on auth failure

- src/app/ErrorView/ErrorView.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/RecordingActions.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Rules/CreateRule.tsx
- src/test/Common.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/EventTypes.test.tsx
- src/test/Events/__snapshots__/EventTypes.test.tsx.snap
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Related to #544 
**Fixes**
- Retry button should only show on auth failture.
- Add missing tests (i.e. checking auth failture view) for `EventTypes` component.
**Chore**
- Use `useSubscriptions` hook where possible in Events/Recordings view.
- Use `React.useMemo` and `React.useCallback` to reduce re-computation of inner functions in Event views.
> fix(auth): only show retry button for auth failures

- src/app/About/About.tsx
- src/app/About/AboutDescription.tsx
- src/app/build.json
- tsconfig.json
Fixes #548
Easy build-time overriding of distribution URLs for bug trackers, mailing list, product name, etc.
> build(config): add build properties JSON file

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Archives/Archives.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Target.service.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
Fixes #549 
**Fixes**
All Archive view now correctly refresh view when auto-refresh is enabled. The issue was that there is a call to `Array.includes`, which only checks object reference.
**Chore**
Counts of archives for each target should not be an saved in an array (i.e. sorting might be supported). Alternative was `Map<string, number>` with key is `target.connectUrl`. This way, subscriptions to notification channel are only called once in `React.useEffect` for each type.
> fix(archive): all-archive should properly display when refreshing

- src/app/Archives/AllArchivedRecordingsTable.tsx
- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Archives/ArchiveDirectoryUtil.tsx
- src/app/Archives/Archives.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/RecordingActions.tsx
- src/app/Recordings/RecordingLabelsPanel.tsx
- src/app/Recordings/ReportFrame.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/Archives/AllArchivedRecordingsTable.test.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
- src/test/Archives/Archives.test.tsx
- src/test/Archives/__snapshots__/AllArchivedRecordingsTable.test.tsx.snap
- src/test/Archives/__snapshots__/AllTargetsArchivedRecordingsTable.test.tsx.snap
- src/test/Archives/__snapshots__/Archives.test.tsx.snap
Fixes #546
Related https://github.com/cryostatio/cryostat/pull/1110
Depends on https://github.com/cryostatio/cryostat/pull/1110
Must be tested with the above back-end PR to work.
> feat(archives): add non-target-specific "all-archives" view

- src/app/Recordings/Filters/DateTimePicker.tsx
- src/app/Recordings/Filters/DurationFilter.tsx
- src/app/Recordings/Filters/LabelFilter.tsx
- src/app/Recordings/Filters/NameFilter.tsx
- src/app/Recordings/RecordingFilters.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/SecurityPanel/Credentials/MatchedTargetsTable.tsx
- src/app/app.css
> fix(recordings): fix recording filters from being cutoff in nested archived recordings tables

- src/app/TargetSelect/TargetSelect.tsx
Related to #544 
#544 removed refresh target button. However, we should still keep the options to auto-refresh target list if enabled.
> fix(target): add back target auto-refresh option

- src/app/Shared/MatchExpressionEvaluator.tsx
> fix(match-exp): match-expression-evaluator handles non-empty match-expr with no target selected

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/Filters/DateTimePicker.tsx
- src/app/Recordings/RecordingFilters.tsx
Fixes #570 
Correctly aligned toolbar items when there is an error text in Datetime Picker. A couple refactoring and quick hack with `align-self` and `InputGroup` solved the issue.
> fix(filters): fix datetimepicker error text alignments

- src/app/Agent/AgentProbeTemplates.tsx
- src/test/Agent/__snapshots__/AgentProbeTemplates.test.tsx.snap
Related to #583
Related to #584 
As a temporary solution, the Probe Template table now has a margin bottom to allow the action menu of the last row to be in viewport. 
I used `1.5em` for bottom, just enough to get the menu in viewport but still looks symmetric with top padding/margin.
Looks like if the xml spans more than 3 rows, the out-of-view-port is not an issue anymore.
> fix(agent): add margin bottom for probe template table

- package.json
- src/app/About/About.tsx
- src/app/Archives/Archives.tsx
- src/app/CreateRecording/CreateRecording.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Events/Events.tsx
- src/app/LoadingView/LoadingView.tsx
- src/app/Login/Login.tsx
- src/app/NotFound/NotFound.tsx
- src/app/Recordings/Recordings.tsx
- src/app/Rules/CreateRule.tsx
- src/app/Rules/Rules.tsx
- src/app/SecurityPanel/SecurityPanel.tsx
- src/app/Settings/Settings.tsx
- src/app/index.tsx
- src/app/routes.tsx
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
- yarn.lock
Fixes #563 
Fixes #587 
- Added configurations to add content-hash to output files and passed the bundle directory to analyzer.
- Applied route-based code splitting: https://reactjs.org/docs/code-splitting.html#route-based-code-splitting. Below is the graph for output bundles sizes:
> build(webpack): code-split bundles and add content-hash to output files

- src/app/Agent/AgentLiveProbes.tsx
- src/app/Agent/AgentProbeTemplates.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/test/Agent/AgentLiveProbes.test.tsx
- src/test/Agent/AgentProbeTemplates.test.tsx
- src/test/Agent/__snapshots__/AgentLiveProbes.test.tsx.snap
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/EventTypes.test.tsx
Fixes #598 
Related to #601 
For consistency, if the table is empty, show an empty state instead of an empty table. Also, rename labels/ids for active probe filters.
> chore(events): use empty state if table is empty

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Fixes #600 
Fixes #603
Related to #605
**Fixes**
- Clean up recording states if there is an error.
- Added an error handler for ArchivedRecordingTable to avoid getting stuck in loading state.
**Chore**
- Remove call to `refreshRecordings` in ArchivedRecording upload table as notifications will handle update.
> fix(recordings): correctly update recording tables on errors

- src/app/RecordingMetadata/RecordingLabelFields.tsx
Fixes #606 
Users can now choose multiple label files to upload into the label editor. This helps avoiding uploading files one by one.
> feat(labels): support multiple metadata label uploads

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Fixes #601 
Hide all toolbars and only show the error view if an error occurs.
For consistency, use upload icon instead of plus icon in upload table.
> chore(toolbar): hide toolbar on errors

- src/test/LoadingView/LoadingView.test.tsx
- src/test/LoadingView/__snapshots__/LoadingView.test.tsx.snap
Fixes #621 
- Added a way to include a descriptive text for spinner. This way, if animations break or using screen reader, users can still see that UI is loading.
- Added a missing unit test for `LoadingView` component.
> chore(loadingview): add descriptive texts for loading spinner

- src/app/Archives/ArchiveUploadModal.tsx
- src/app/RecordingMetadata/RecordingLabel.tsx
- src/app/RecordingMetadata/RecordingLabelFields.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Fixes #623 
Handled parsing error if user uploads invalid metadata label files. The invalid files are shown in a popover on top of the button since inline texts are taking quite some spaces and misaligned. In the background, invalid file contents are ignored (i.e. return empty []).
> fix(label-upload): add error handler for metadata uploads

- package.json
- yarn.lock
Related to #629
Remove unused dependency. Express is a web framework for server-side (Node) applications. This project is only built to static assets to be served by the Cryostat backend and we never use Express for anything.
> build(deps): remove unused express dep

- src/app/Settings/CredentialsStorage.tsx
- src/app/Shared/Services/JmxCredentials.service.tsx
- src/test/Settings/CredentialsStorage.test.tsx
- src/test/Settings/__snapshots__/CredentialsStorage.test.tsx.snap
Related to #656 
Use Backend storage as default. This does not fix the issue but just switch it default Backend.
> fix(credentials): set backend storage as default

- src/app/AppLayout/AppLayout.tsx
- src/app/AppLayout/AuthModal.tsx
- src/app/AppLayout/JmxAuthForm.tsx
- src/app/SecurityPanel/Credentials/CreateJmxCredentialModal.tsx
- src/app/SecurityPanel/Credentials/StoreJmxCredentials.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/SecurityPanel/Credentials/StoreJmxCredentials.test.tsx
Related to #640 
- Refactored auth form to avoid using promise (previously used for updating form states).
- Added error handlers for recording creation form (was accidentally not committed in #640).
> chore(auth): refactor auth form to avoid promise updates

- src/app/index.tsx
- src/test/Agent/AgentLiveProbes.test.tsx
- src/test/Agent/AgentProbeTemplates.test.tsx
- src/test/Archives/AllArchivedRecordingsTable.test.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
- src/test/Archives/Archives.test.tsx
- src/test/Common.tsx
- src/test/CreateRecording/CustomRecordingForm.test.tsx
- src/test/Dashboard/Dashboard.test.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/EventTypes.test.tsx
- src/test/RecordingMetadata.tsx/BulkEditLabels.test.tsx
- src/test/Recordings/Recordings.test.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/Rules/Rules.test.tsx
- src/test/SecurityPanel/Credentials/StoreJmxCredentials.test.tsx
- src/test/Settings/CredentialsStorage.test.tsx
- src/test/TargetSelect/TargetSelect.test.tsx
Fixes #610 
Added Notification context provider so that `useContext` will pull from there. For tests, custom render functions are now wrapped in this provider.
> chore(context): add notification context provider

- src/app/Rules/CreateRule.tsx
- src/app/Rules/RulesUploadModal.tsx
- src/test/Rules/Rules.test.tsx
> fix(rules): rename Automatic to Automated

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/SnapshotRecordingForm.tsx
- src/app/ErrorView/ErrorView.tsx
- src/test/CreateRecording/CustomRecordingForm.test.tsx
- src/test/CreateRecording/SnapshotRecordingForm.test.tsx
- src/test/CreateRecording/__snapshots__/SnapshotRecordingForm.test.tsx.snap
Fixed #673 
Fixed #686 
The following fixes were applied:
Others:
> fix(create-recordings): add error-views and refactor target listener

- .github/.labeler.yml
- .github/workflows/pr-labeler.yml
- .mergify.yml
Fixes: #696
This change reverts mergify from adding the needs triage label to pull requests.
Mergify kept adding the label, which failed the CI, but removing the label would cause Mergify to add it back.
1. Start a pull request as a non-cryostat-reviewer. 
2. Notice that mergify doesn't add the label anymore.
> chore(mergify): revert mergify to stop automatically adding needs-triage label

- .github/workflows/check-labels.yml
- .github/workflows/ci.yaml
Fixes: #696 
Puts label check in separate workflow.
GitHub CI notice changes in labels until seemingly being notified from the `labeled` event.
https://github.com/maxcao13/cryostat-web/pull/5
This will result in the CI tests to still run if the label is present or not.
> fix(ci): add new workflow which checks if needs-triage is not present

- src/app/Shared/Services/Api.service.tsx
Related to https://github.com/cryostatio/cryostat/pull/1257
Depends on #699 (updating ci)
This added a parameter to `sendRequest` function in Api.services to allow skipping status code check (i.e. internal error handler).
Since https://github.com/cryostatio/cryostat/pull/1257, target creation now allows `dryrun`. Auth failure (i.e. status 427) during `dryrun` should not trigger Auth modal, which is the default behaviour. This flag will allow disable this behaviour if needed.
Not yet used anywhere until #592.
> chore(requests): allow skipping status code check

- src/app/Agent/AgentProbeTemplates.tsx
- src/test/Agent/AgentProbeTemplates.test.tsx
Fixes: #586 
Depends on https://github.com/cryostatio/cryostat/pull/1273
This change clean up notification handling in the AgenTemplate table to use notification message and patch the table without refreshing.
- Avoid unncessary api requests and allow smoother UI.
- Upload modal is uncessarily unmounted due to refeshing causes loading view to render. This fix will avoid this, allowing the modal to keep local states (to display failed files).
1. Start the backend with latest changes from https://github.com/cryostatio/cryostat/pull/1273. For example:
```
$ CRYOSTAT_IMAGE=ghcr.io/cryostatio/cryostat:pr-1273-254d0939d87cfa7940d734311b06d959f58d7cdc sh smoketest.sh
```
3. Delete or add templates. 
4. All functionality should remain the same. 
5. …
> chore(agent): use notification message to patch template table

- src/app/Agent/AgentLiveProbes.tsx
- src/app/Agent/AgentProbeTemplates.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/Agent/AgentLiveProbes.test.tsx
- src/test/Agent/__snapshots__/AgentLiveProbes.test.tsx.snap
Related to #640 
Related to #586 
Related to #584 
Depends on https://github.com/cryostatio/cryostat/pull/1280
The Active Probe table's action buttons do not have spinner added. Must have been left out previously. Action buttons should all be disabled when in progress.
Also, this includes the final piece of clean up for notifications handling for agent UI.
1. Run Cryostat backend with a jmc agent attached.
2. Go to Events -> Agent Template/Live Configurations table.
> perf(agent-probe): patch state with notification and add spinner

- src/app/Agent/AgentLiveProbes.tsx
- src/app/Agent/AgentProbeTemplates.tsx
- src/app/Archives/ArchiveUploadModal.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Modal/CancelUploadModal.tsx
- src/app/Rules/RulesUploadModal.tsx
- src/app/SecurityPanel/CertificateUploadModal.tsx
- src/app/Shared/FileUploads.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/Agent/AgentProbeTemplates.test.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/__snapshots__/EventTemplates.test.tsx.snap
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Rules/Rules.test.tsx
Fixes #613 
Partially solved #651 
Related to #607 
Depends on #684 (need that refactoring of upload modals)
Depends on #708 (refresh causes modal to close unexpectedly)
Depends on https://github.com/cryostatio/cryostat/pull/1273 (backend for #708)
The following upload modals now allow multiple uploads. Each file initiates a separate api request.
One issue is that fetch API does not have support for upload progress yet (or only certain browser versions have support). To work around this, I "mirrored" the current `sendRequest` to one that uses `XMLHttpRequest`. This way we can take advantage of upload progress and guarantee support from most browsers. 
Also, by using XMLHttpRequest, we can no longer use `AbortController` for aborting. Aborting mechanisms need investigating and adding back …
> feat(uploads): allow users to upload multiple files

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Shared/Redux/DashboardConfigActions.tsx
- src/app/Shared/Redux/DashboardConfigReducer.tsx
Related to #727
This change adds a step to the Add card on the Dashboard. The new step builds a dynamic form for configuring
the selected card type. This form becomes `props` passed to the card(s) when created. This configuration is
stored in the Redux store and persisted to localstorage along with the previous implementation's simple linear
layout of card names, so the configuration props are also persistent.
This allows more flexibility for card implementations with multiple instances since the instances can be
distinguished simply by props rather than needing to implement more complex partitioning of the Redux store.
This will also be useful for configuration of card sizes in the dynamic grid layout. For the Grafana cards
we have …
> feat(dashboard): card configuration

- .github/dependabot.yml
- .github/workflows/labeler.yml
Fixes: #759 
Allows dependabot to add safe-to-test label to it's PRs and makes the labeler only call its workflow on `open` and `reopen` actions.
This change is helpful because dependabot shouldn't be blocked and the labeler shouldn't be spamming needs-triage whenever people do actions that don't require triage.
1. Not applicable.
> fix(ci): small ci fixes

- src/app/Rules/CreateRule.tsx
- src/test/Rules/CreateRule.test.tsx
Fixes: #766 
Previously, name input validation was not checking new input name due to using incorrect variable name. This causes unusual behaviour as described in the issue.
1. Run smoketest
2. Go to `Automated Rule` tab. Click Create.
3. Enter invalid name => show error helper text.
4. Past a valid name => show successful indicator.
5. Same for matchExpression input.
> fix(rules): fix rule form validation

- src/app/About/AboutCryostatModal.tsx
Fixes: #768 
Added a custom background image for our Cryostat about modal.
Cryostat needs its own background image instead of the Patternfly default.
1. `Run CRYOSTAT_IMAGE=<gh-action-image> sh smoketest.sh`
2. Go top top-right and click on the`?` icon .
3. See the new modal with latest background image.
> chore(about): use cryostat custom background in about modal

- src/app/AppLayout/AppLayout.tsx
- src/app/Shared/FeatureFlag/FeatureFlag.tsx
Related to #761
Quick refactoring. Adds a new feature flag component type which is gated on a list of accepted levels and requires a prop function that generates the flagged component from the active level. This allows the flagged component to adapt to the active level rather than requiring separate definitions of a component for each level. In most cases the previous "static" `<FeatureFlag></FeatureFlag>` component should be preferred.
> chore(featureflags): add dynamic flag wrapper component

- src/app/Agent/AgentLiveProbes.tsx
- src/app/Agent/AgentProbeTemplates.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Modal/DeleteWarningModal.tsx
- src/app/Modal/DeleteWarningUtils.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Rules/RuleDeleteWarningModal.tsx
- src/app/Rules/Rules.tsx
- src/app/SecurityPanel/Credentials/StoreJmxCredentials.tsx
- src/app/Settings/DeletionDialogControl.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Settings.service.tsx
- src/app/TargetSelect/TargetSelect.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Rules/Rules.test.tsx
- src/test/SecurityPanel/Credentials/StoreJmxCredentials.test.tsx
Related to https://github.com/cryostatio/cryostat/pull/1289
See https://github.com/cryostatio/cryostat/issues/1283
1. Go to Automated Rule tab
2. Create or enable a existing rule.
3. Now toggle the rule to disable it. The modal should show up.
> feat(rules): allow cleanup resources when disabling automated rules

- .gitignore
- webpack.common.js
- webpack.prod.js
Fixes: #790 
Enable production build cache.
See #790 
Build with:
```bash
yarn build:notests
```
Then, rebuild without changing any source files and observe the time taken.
> build(webpack): cache production builds

- src/app/TargetSelect/TargetSelect.tsx
Partial fixes: #805 
Related to: https://github.com/cryostatio/cryostat/pull/1327 (WS notifications should be sent).
Update target cache to save only connectUrl and should update currently selected target with new details.
See #805
2.  Choose any target with credentials. Either enter credentials using Auth modal or add in Security Panel.
3. Expand the target details. See the jvmId being updated.
> fix(target): update target selection cache

- src/app/Dashboard/Dashboard.tsx
- src/app/Dashboard/DraggableRef.tsx
Fixes: #729
Related to: #796 
This change allows cards to be resized when they are close to the edge of the screen.
1. Have 2 cards, and make the second card large enough to overflow to the next row. This wasn't able to be done before because of some refactoring.
> fix(dashboard): allow cards to overflow when resized

- src/app/Shared/Services/NotificationChannel.service.tsx
- src/app/Shared/Services/Targets.service.tsx
Fixes #805 
Depends on https://github.com/cryostatio/cryostat/pull/1327
Added a new event kind for target's modified state.
This will help avoid `TargetSelect` deselect the target due `LOST` notification (previously consecutive `LOST` + `FOUND` on the same target = `MODIFIED`).
2. Try select a target with authentication with no saved credentials.
3. Enter the credentials.
4. Observe the modified notification
5. Target is still selected.
> feat(target): add target event kind for modified state

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/Recordings.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
Related to #811 
After some previous refactoring jobs, the Archive table now accepts a target prop that select a target to pull archive from. However, that seems to introduce problems with hook deps. 
#811 fixes the hook deps issue for upload table but `Archive table` & `All Targets` (additionally, count number is not updated correctly) suffers the same problem. `All Archives` table seems to be safe since it refreshes everything on any updates.
This leads to duplicate archive recording rows when testing with https://github.com/cryostatio/cryostat/pull/1333
> fix(archives): fix duplicate archived recording displays

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Dashboard/DashboardCard.tsx
- src/app/Dashboard/DraggableRef.tsx
- src/app/Dashboard/ResizableRef.tsx
- src/app/Shared/Redux/Configurations/DashboardConfigSlicer.tsx
- src/app/app.css
- src/app/utils/utils.ts
- src/test/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Fixes: #730 
This change allows cards to be re-orderable with drag-and-drop swapping functionality. 
Again, no tests since beta dashboard functionality is likely to be changed in the future.
When create DashboardCards, you must pass in a `CardHeader` into the `cardHeader` prop.
See #730
1. Run normal smoketest and add some cards, and rearrange them by holding the top draggable bar and drag and dropping them around on top of each other to swap the cards places. You can also drag cards between other cards to rearrange them.
> feat(dashboard): allow drag-and-drop reordering of dashboard cards

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/Filters/DatetimeFilter.tsx
- src/app/Recordings/RecordingActions.tsx
- src/app/Recordings/RecordingFilters.tsx
- src/app/Recordings/Recordings.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Rules/Rules.tsx
- src/app/TargetView/TargetView.tsx
- src/test/Common.tsx
- src/test/Dashboard/__snapshots__/Dashboard.test.tsx.snap
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Recordings/__snapshots__/Recordings.test.tsx.snap
- src/test/Rules/__snapshots__/Rules.test.tsx.snap
Fixes: #828 
The issue is quite severe for the Rule table as regular viewport also make it overflow. This PR addresses that and original issue with overflowing toolbar.
2. Go to Automated Rule tab and create a rule if not any. See the table is not scrollable.
3. Go to Recording Tab. Reduce the screen viewport. See the buttons collapsing into a dropdowm
**Collapsed toolbar:**
**Collapsed Toolbar action buttons:**
**Scrollable Automated table:**
> fix(layout): fix content overflow

- package.json
- webpack.dev.js
Fixes: #854 
This change adds an env variable that can be passed in to enable eslint for development. There is also a new react script which does this for you `yarn start:dev:lint`
See #854 
1. Try both configurations. `yarn start:dev` and `yarn start:dev:lint` (or `ESLINT_ENABLE=true yarn start:dev`). One will use eslint, the other won't.
> chore(dev): `ESLINT_ENABLE` option and `yarn start:dev:lint` script

- src/app/Rules/Rules.tsx
- src/test/Rules/Rules.test.tsx
- src/test/Rules/__snapshots__/Rules.test.tsx.snap
Related to #846 
Depends on #858 
With the table being wrapped in `<InnerScrollContainer />`, action menu is shown inline, making the users scroll down to see. With these changes, the menu should be shown over the table.
**Previously**
**After changes**
> fix(rules): action menu should not be inline

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Dashboard.tsx
Related to #840
Wrap dashboard cards in a `<FeatureFlag/>` so that they are only rendered if their configuration defines them part of the current feature level or higher. The dashboard layout is not actually modified in storage, the elements are only skipped when the component tree is being built, so if the user returns back to a lower feature level then the cards will reappear.
TODO later: add some visual indicator, like a badge in the card header matching the one in the application masthead, or a colour-coded border matching that badge, on each card so that it is obvious to the user that the cards they are using may not be production features. In this PR the user can only discover this by toggling the feature level and checking what …
> feat(dashboard): wrap cards in feature flag

- src/app/Agent/AgentLiveProbes.tsx
Fixes: #893 
Take into account the current global target selection when updating probe table.
See #893
> fix(agent): patch event should consider current target selection

- locales/en/common.json
- src/app/BreadcrumbPage/BreadcrumbPage.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
- src/app/Dashboard/DashBoardSolo.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Dashboard/DashboardCard.tsx
- src/app/Dashboard/DashboardCardActionMenu.tsx
- src/app/Dashboard/Quickstart/QuickStartsCard.tsx
- src/app/Shared/MatchExpressionEvaluator.tsx
- src/app/Topology/Shared/utils.tsx
- src/app/routes.tsx
- src/test/Dashboard/Charts/jfr/__snapshots__/JFRMetricsChartCard.test.tsx.snap
- src/test/Dashboard/Charts/mbean/__snapshots__/MBeanMetricsChartCard.test.tsx.snap
Fixes: #739 
Added a subroute to view the card in "full-screen" mode. This approach is similar to Grafana Dashboard. The route requires a query paramter `cardId` to find the card configuration. If none or invalid, an empty state will be shown.
See #739 
1. Create any dashboard card.
2. Click on top-right kebab icon to show action.
3. Click `View` to see full mode.
4. Notice the breadcrumb has the card Id (same as query param) and allows going back to main dashboard.
> feat(dashboard): full view dashboard card

- src/app/Dashboard/JvmDetails/JvmDetailsCard.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Topology/Actions/NodeActions.tsx
- src/app/Topology/GraphView/CustomGroup.tsx
- src/app/Topology/GraphView/UtilsFactory.tsx
- src/app/Topology/ListView/UtilsFactory.tsx
- src/app/Topology/Shared/Entity/EntityDetails.tsx
- src/app/Topology/Shared/Entity/utils.ts
- src/app/Topology/Shared/utils.tsx
- src/app/Topology/Topology.tsx
- src/app/Topology/styles/base.css
- src/app/Topology/typings.ts
Fixes: #901 
Depends on https://github.com/cryostatio/cryostat/issues/1403
Depends on https://github.com/cryostatio/cryostat/issues/1410
Depends on https://github.com/cryostatio/cryostat/pull/1411
Depends on https://github.com/cryostatio/cryostat/pull/1417
Note: Fail operations on an individual target (e.g. missing credentials) are silent (even notifications are not shown). Any idea to check errors?
See #901 
2.  Go to Topology View
> feat(topology): group node actions

- src/app/Topology/Shared/TopologyEmptyState.tsx
Related to: #891 
Added missing callback to empty state
Empty state actions should perform work as expected.
1. Go to Topology -> Select listview -> type any words in search bar -> clear searches
2. Go to Topology -> Select graphview -> choose a bad filter (a target + a group not containing the target) -> clear filters.
> fix(topology): add missing callbacks to empty state actions

- src/app/Topology/Actions/CreateTarget.tsx
- src/app/Topology/GraphView/CustomNode.tsx
- src/app/Topology/GraphView/NodeDecorator.tsx
- src/app/Topology/Shared/Entity/EntityDetails.tsx
- src/app/Topology/Shared/Entity/EntityTitle.tsx
- src/app/Topology/Shared/Entity/utils.tsx
- src/app/Topology/Shared/HintBanner.tsx
- src/app/Topology/Toolbar/QuickSearchButton.tsx
- src/app/Topology/Toolbar/TopologyToolbar.tsx
- src/app/app.css
- src/app/index.tsx
Depends on https://github.com/cryostatio/cryostat/issues/1428
Each resource row can have an expanded section that show detail view. For now, only `ActiveRecording` row is supported. Others will show an empty text.
See https://github.com/cryostatio/cryostat-web/pull/906#issuecomment-1472888342
> feat(topology): expanded row for resource details

- package.json
- src/app/app.css
- src/app/routes.tsx
- webpack.common.js
- yarn.lock
Fixes: #863 
Revert any route code-splitting. This way all modules are combined into a single chunks and css order is correct.
Code-splitting causes css splitting also causes incorrect css order.
```
$ ls -lst dist/
total 24888
... Some other npm chunks
4364 -rw-r--r--. 1 thvo thvo 4464935 Mar 28 16:31 app.42655dbd468f507b.bundle.js # Single main chunk here
16 -rw-r--r--. 1 thvo thvo   15294 Mar 28 16:31 app.ca8cbbf143633cc9.bundle.css # Single main css chunk here
7044 -rw-r--r--. 1 thvo thvo 7212327 Mar 28 16:31 npm.patternfly.b80ecc5a3ab05a91.bundle.js
4 -rw-r--r--. 1 thvo thvo    1994 Mar 28 16:31 runtime.1faec187d6b6f3ff.bundle.js
12 -rw-r--r--. 1 thvo thvo    8800 Mar 28 16:31 index.html # No prefetch
48 -rw-r--r--. 1 thvo thvo   46149 …
```
> fix(webpack): revert code splitting routes

- src/app/Topology/Actions/QuickSearchPanel.tsx
- src/app/Topology/Actions/utils.ts
Mini quick search (opened by right click on topology view) needs to check for active feature level.
Right now, it does not check so all quick searches are allowed.
Considering BETA level, the dev sample is DEVELOPMENT level.
> fix(topology): mini quicksearch should check active feature level

- src/app/Shared/MatchExpression/MatchExpressionVisualizer.tsx
- src/app/Topology/Actions/WarningResolver.tsx
- src/app/Topology/GraphView/TopologyGraphView.tsx
- src/app/Topology/Shared/Entity/EntityDetails.tsx
- src/app/Topology/SideBar/TopologySideBar.tsx
- src/app/Topology/Topology.tsx
- src/app/Topology/styles/base.css
Add some css rules to allow detail content to be scrollable. This prevents the topology view from stretching the visualization surface, causing control bar to be pushed down.
Nicer UX and closer to OCP design. But there is one difference. For OCP, the whole sidebar is scrollable, including headers and close button. For cryostat, only the sidebar content body is scrollable (all below the tab bar).
> fix(topology): scrollable detail sidebar

- src/app/AppLayout/AppLayout.tsx
- src/app/Archives/Archives.tsx
- src/app/Events/Events.tsx
- src/app/Recordings/Recordings.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Settings/AutoRefresh.tsx
- src/app/Settings/AutomatedAnalysisConfig.tsx
- src/app/Settings/ChartCardsConfig.tsx
- src/app/Settings/CredentialsStorage.tsx
- src/app/Settings/DatetimeControl.tsx
- src/app/Settings/DeletionDialogControl.tsx
- src/app/Settings/FeatureLevels.tsx
- src/app/Settings/Language.tsx
- src/app/Settings/NotificationControl.tsx
- src/app/Settings/Settings.tsx
- src/app/Settings/SettingsUtils.ts
- src/app/Settings/Theme.tsx
- src/app/Settings/WebSocketDebounce.tsx
- src/app/Topology/Shared/Entity/utils.tsx
- src/app/app.css
- src/app/utils/utils.ts
- src/test/Archives/Archives.test.tsx
- src/test/Archives/__snapshots__/Archives.test.tsx.snap
- src/test/Recordings/Recordings.test.tsx
- src/test/Recordings/__snapshots__/Recordings.test.tsx.snap
- src/test/Settings/Settings.test.tsx
Fixes: #78 
Depends on: #925 (This PR includes refactoring to Settings and tab renaming).
Tab-based views are now routable using query paramter:
Invalid tab query param will cause the view to fall back to the first tab. This way we don't have to handle error and show empty state and the user do not have to manually clean up url.
This allows users to bookmark urls for later without having to click on tabs. This would mean the user can use back-button to go back to previous (very nice UX if users have back-button on mouse).
2. Go to any route with tab-based view (e.g. Recordings). Change tab and notice the query param changes.
3. Try bookmark/save the url with tab query param. Then visit it …
> feat(router): routable views

- README.md
- locales/en/common.json
- locales/en/public.json
- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartController.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartController.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Dashboard/DashboardCard.tsx
- src/app/Dashboard/DashboardLayoutConfig.tsx
- src/app/Dashboard/JvmDetails/JvmDetailsCard.tsx
- src/app/QuickStarts/QuickStartDrawer.tsx
- src/app/QuickStarts/quickstarts/dashboard-quickstart.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Topology/Actions/NodeActions.tsx
- src/app/Topology/Shared/Entity/utils.tsx
- src/app/Topology/SideBar/TopologySideBar.tsx
- src/app/Topology/Toolbar/QuickSearchButton.tsx
- src/app/Topology/Toolbar/TopologyToolbar.tsx
- src/app/Topology/styles/base.css
- src/app/app.css
- src/app/utils/fakeData.ts
- src/test/Dashboard/DashboardLayoutConfig.test.tsx
- src/test/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Related to #468
See https://github.com/cryostatio/cryostat-web/issues/727#issuecomment-1355724879
> feat(dashboard): dashboard card catalog

- locales/en/common.json
- src/app/DateTimePicker/TimezonePicker.tsx
Fixes: #938 
Lazy load timezone options. This way, first load will be quicker. 
**Note**: This added a new select item that serves as a placeholder. PF examples use `loadingVariant`, however, there is a small bug that causes `View More` to be hidden when used with inline filter (only happens on first build/render). Also, search filter will exclude options that are not shown yet.
See #938
2.  Go to Settings.
3.  Notice the setting page loads faster.
4. Click on the timezone picker and scroll down to see the View More item.
5. Click on it will make the option list expands. This View More is only available when list is not fully shown
> fix(settings): lazy load timezones

- locales/en/common.json
- locales/en/public.json
- src/app/Shared/ErrorBoundary.tsx
- src/app/routes.tsx
Related to: #950 
Add an error boundary around component that renders the main container view. Though, this won't completely fix the issue because we need consider more granular handling.
**Note**: this applies for first render. If later one child components build fail, no error views will be shown.
> Also bear in mind that try/catch blocks won't work on all cases.
> If a component deep in the hierarchy tries to updates and fails, the try/catch block in one of the parents won't work -- > ? because it isn't necessarily updating together with the child.
See #950. This applies to first renders to that errors are caught early.
2. Try:
```diff
diff --git a/src/app/Dashboard/Dashboard.tsx …
```
> feat(error): set error boundary for first renders

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Shared/Services/Target.service.tsx
Temporary fixes for #944 
Use a special error message for http-based targets.
See #944 
2. Go to Recording tab -> Create Recording -> Select `9988` (http).
3. See the error message.
|Dark Theme | Light Theme |
|---|---|
|![Screenshot from 2023-04-14 15-09-20](https://user-images.githubusercontent.com/68053619/232134997-6bafec7e-303c-499e-8c84-58117388e644.png)|![Screenshot from 2023-04-14 15-09-51](https://user-images.githubusercontent.com/68053619/232135094-f2938dc8-a5f5-434c-8463-cc35311f1457.png)|
> fix(recordings): use a helpful error messge for http-based targets

- src/app/Rules/Rules.tsx
Fixes: #959
The change fixes the bug where enabling and disabling rules will cause them to move to the bottom of the rules table. I've not gone through with allow users to sort on enable/disable because the rule table state depends on the response from the backend so if the sort===enabled, toggling the button would always keep the rows in a sorting state and cause the table rows to jump around, but if state was managed by the front-end, enabling/disabling rules would hopefully just remove the sorting state entirely until the user wants to sort again by pressing the sort arrows.
Go to rules table and enable/disable rules. Rules no longer jump around.
> fix(rules): fix enable/disable rules cause them to jump on Rules table

- src/app/Topology/Topology.tsx
Add an effect that set interval to refresh the discovery tree if enabled.
Missing auto-refresh. If not set, topology view never update if notification socket is not enabled or working.
> fix(topology): topology view should auto-refresh if enabled

- src/app/Agent/AgentLiveProbes.tsx
- src/app/Agent/AgentProbeTemplates.tsx
- src/app/Archives/AllArchivedRecordingsTable.tsx
- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Events/EventTypes.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Rules/Rules.tsx
- src/app/SecurityPanel/Credentials/CredentialTestTable.tsx
- src/app/SecurityPanel/Credentials/MatchedTargetsTable.tsx
- src/app/SecurityPanel/Credentials/StoreCredentials.tsx
- src/app/utils/utils.ts
- src/test/Rules/Rules.test.tsx
Related to #960 
Saw Max's PR on the issue with rule update causes it to be pushed the end. I think it was due to notification handler just placing it at the end. This PR updates that to retain the position.
However, there are no guarantee that next time it reloads, the row order will be the same. This issue also affects other tables (e.g. archives). But @maxcao13 fixed this by setting initial sort order for rule table (thanks!). So, this PR also includes initial sort for other tables to completely capture this problem. Tho, there is a small implication that any newly added resource (i.e. recording, rule) is subjected to sort and no longer appended to the end.
There is also an issue with sort handler when sorting file names including …
> fix(tables): table should have an intial sort order

- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCardList.tsx
- src/app/Dashboard/AutomatedAnalysis/ClickableAutomatedAnalysisLabel.tsx
- src/app/Dashboard/dashboard-utils.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/Dashboard/AutomatedAnalysis/__snapshots__/AutomatedAnalysisCardList.test.tsx.snap
Related: https://github.com/cryostatio/cryostat/pull/1457
Depends on: https://github.com/cryostatio/cryostat/pull/1457
Fixes icons for AA results to fit the result (warning = warningTriangleIcon, error = exclamation point).
This PR also has a hack to separate Summary and Explanation within description of Rule results.
> fix(dashboard): fixup Automated Analysis Card

- src/app/AppLayout/AppLayout.tsx
- src/app/Settings/Settings.tsx
- src/app/Settings/SettingsUtils.ts
- src/app/routes.tsx
- src/app/utils/useFeatureLevel.ts
- src/app/utils/useLogin.ts
- src/test/Settings/Settings.test.tsx
- src/test/Settings/__snapshots__/Settings.test.tsx.snap
Fixes: #981 
Annotate each setting (requires auth) with `authenticated` field. These settings are hidden when the user is logged out.
When the user logs in, the settings are shown as usual.
See #981 
|Before|After|
|--|--|
|![Screenshot from 2023-04-24 23-53-38](https://user-images.githubusercontent.com/68053619/234182019-a206b809-b889-4902-b2e6-c73ef2022f78.png)|![Screenshot from 2023-04-25 01-25-06](https://user-images.githubusercontent.com/68053619/234182005-9cee3fe6-028c-4740-9384-b6d14f404aaa.png)|
> fix(settings): hide settings that requires auth for logged-out user

- src/app/Topology/styles/base.css
Added a fixed height for entity detail in Topology List View. This allows list view to show JVM detail.
There was a fix for JVM Detail card in #937 but that PR missed the fix for Topology ListView.
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/68053619/234149872-7da87635-1ed1-4a35-8e7f-ce0ca655ff4b.png)|![Screenshot from 2023-04-24 21-52-26](https://user-images.githubusercontent.com/68053619/234155048-99c0ac74-f276-41f3-ad30-5e6cd2b05d6c.png)|
> fix(topology): listview target details need fixed height

- src/app/AppLayout/AppLayout.tsx
- src/app/Settings/Settings.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/utils/utils.ts
Fixes: https://github.com/cryostatio/cryostat/pull/1457
Forgot that the web-client actually uses the archived directory get response data to request for editing labels, viewing reports, and reviewing recordings in Grafana, per target. Particularly the subdirectoryName, since it is now replaced by the jvmId, should be converted like how the backend does it.
Before this change, the requests failed.
1. Go to archives view: try editing labels, view report, viewing recording in grafana
> fix(archives): convert jvmId to subdirectoryName for web-client requests

- src/app/routes.tsx
Fixes: #994 
Allow seeing `/about` route without logging in.
See #994
> fix(about): route /about should show without auth

- locales/en/public.json
- src/app/Archives/ArchiveUploadModal.tsx
- src/app/RecordingMetadata/RecordingLabel.tsx
- src/app/RecordingMetadata/RecordingLabelFields.tsx
Fixes: #997
The change reverts ArchiveUploadModal to append to document body for the popover to show again. I cannot figure out quite the reason why appending the modal to portalRoot makes popperjs think that the popper is being cutoff in some way.
According to an [article](https://dev.to/atomiks/everything-i-know-about-positioning-poppers-tooltips-popovers-dropdowns-in-uis-3nkl) I read: 
```
Popper attaches attributes in the following cases:
data-popper-escaped: When the popper escapes the reference element's clipping container (it appears detached)
data-popper-reference-hidden: When the reference element is hidden from view (it appears attached to nothing)
```
But it doesn't seem the reference is ever hidden from view, even when the …
> fix(uploads): fix archive upload modal invalid labels popover 

- src/app/Settings/Settings.tsx
- src/app/Shared/TargetSelect.tsx
- src/app/app.css
- src/test/Settings/__snapshots__/Settings.test.tsx.snap
Related to #793 
Unmount setting tab content that is not selected. This helps avoid situation where AA configurations cause the Auth modal to appear when first visiting `/settings` (users might wonder why this opens as they don't see the AA config). This also allows faster load as React only needs to build 1 tab content at a time.
Extend the min height for local target select to show more targets (currently it looks like, without scrolling, there is a single target).
AA configurations causes the setting page to show Auth modal even if the AA configuration is not visible (i.e. Dashboard tab not selected).
> fix(settings): set unmountOnExit behaviour for setting groups

- src/app/Topology/Actions/QuickSearchPanel.tsx
- src/app/Topology/Toolbar/QuickSearchButton.tsx
- src/app/Topology/styles/base.css
Related to #1008 (Thanks Max for figuring out the root issue of element focus).
Mount tooltip closer to the catalog button (modal will clip this tooltip -> close tooltip). Also, unfocus the catalog button -> do not persist tooltip.
Also, fix a css issue where the rules is not applied to the catalog button causing it to have padding.
Catalog button is showing the tooltip over the modal and persist the tooltip after closing modal. We should avoid this.
> fix(topology): catalog btn tooltip should not show if not needed

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
Fixes: #1023 
Related to: #1008
- Separate display from actual select option value + fix default value for `themeColor` prop selection.
- Add static type to parameters and component.
See #1023 
https://www.patternfly.org/v4/components/select/#selectoption
> fix(dashboard): separate display from actual option value

- .github/workflows/ci.yaml
- .github/workflows/pr-ci.yml
Fixes: #1017 
- Split test ci steps into jobs that can be run in parallel.
- Remove `yarn build:notests` as a step since we don't need to build the asset for any tests.
- Set node version to `16.18.x` (cryostat builds use node `16.18.1`).
See #1017
> chore(ci): run testing jobs in parallel

- src/app/Topology/Actions/NodeActions.tsx
Related to #906 
Disable gorup node actions while performing check with backend.
In cases where network is slow, the users will not be able to perform actions when the checking is in progress.
> chore(topology): disable group node actions while checking

- src/app/SecurityPanel/ImportCertificate.tsx
- src/app/Topology/Shared/Entity/EntityDetails.tsx
- src/app/Topology/Shared/utils.tsx
Fixes: #1033 
Add an option to add certificates when JVM ID cannot be computed. Also, a small warning icon next to JVM ID if empty.
See #1033
> fix(topology): warning resolver should include adding ssl certs

- .github/workflows/ci-preview.yml
Related to #1046 
Update path matching to include all under `src`.
Preview CI should target all under `src` because there are also i18next and mirage codes.
> fix(ci): preview ci should target all under src

- jest.config.js
- src/app/Shared/Services/Login.service.tsx
- src/test/Shared/Services/Login.service.test.tsx
Fixes: https://github.com/cryostatio/cryostat/issues/1489
On OpenShift, `setLoggedOut` now submits a form to the logout endpoint of OpenShift's OAuth server. This avoids making a CORS request and passes the `HttpOnly` session cookie to the endpoint. I added several new test cases that test logging out with both Basic and Bearer methods.
This fixes a bug where users on OpenShift could not log out without manually deleting cookies.
1. Have a running OpenShift cluster.
2. Build a Cryostat image including this fix (or use mine: `quay.io/ebaron/cryostat:logout-test-web-10`).
3. Deploy the operator using this image: `make deploy CORE_IMG=quay.io/ebaron/cryostat:logout-test-web-10`, substituting the image from step 2 if needed.
4. Log into Cryostat …
> fix(login): submit form to log out from OpenShift OAuth

- src/app/Rules/CreateRule.tsx
- src/app/SecurityPanel/Credentials/CreateCredentialModal.tsx
- src/app/SecurityPanel/Credentials/CredentialTestTable.tsx
- src/app/SecurityPanel/Credentials/StoreCredentials.tsx
- src/app/Shared/MatchExpression/MatchExpressionVisualizer.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Topology/GraphView/CustomNode.tsx
- src/app/Topology/GraphView/TopologyGraphView.tsx
- src/app/Topology/ListView/TopologyListView.tsx
- src/app/Topology/ListView/UtilsFactory.tsx
- src/app/Topology/Shared/utils.tsx
- src/app/Topology/Toolbar/FindByMatchExpression.tsx
- src/app/utils/utils.ts
- src/test/Rules/CreateRule.test.tsx
- src/test/SecurityPanel/Credentials/StoreCredentials.test.tsx
Fixes: #1067 
Depends on https://github.com/cryostatio/cryostat/issues/1601
Update front-end handler for async checks when evaluating match expression (i.e. done on server via endpoint `/api/beta/matchExpression`)
See #1067
> feat(match-expression): match expression should be evaluated on backend

- src/app/Modal/DeleteWarningUtils.tsx
Fixes: #1042 
Depends on #1070
*[Bug] Warning modal for disabling rule should say "disable" instead of "delete"
> fix(modal): Warning modal for disabling rule should say "disable" instead of "delete"

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
- src/app/Dashboard/ErrorCard.tsx
- src/app/Dashboard/JvmDetails/JvmDetailsCard.tsx
- src/app/Dashboard/LayoutTemplateUploadModal.tsx
- src/app/Dashboard/dashboard-utils.tsx
- src/app/Shared/Redux/Configurations/DashboardConfigSlice.tsx
Fixes: #1079 
With help from Thuan, we figure out the bug. This change replaces all instances where we reference the Functional component name as data related to the dashboard. We need to do this because, it seems like Webpack minifys all instances of the component name in production mode: https://stackoverflow.com/questions/43800784/get-component-name-in-react. And then we end up with weird names and bad states because of this. That's also why there was no bug if running the `yarn start:dev` dev server.
1. CD to a cryostat repo.
2.  `cd web-client` and checkout this branch in that submodule e.g. `git checkout f8592d891067c18a1f61f0cdbabc995974e56944`
3. cd back to `..` and run `mvn clean -DskipTests package`
4. Clear browser localstorage on …
> fix(cards): replace instances of card.component.name

- package.json
- src/app/utils/utils.ts
- yarn.lock
Related to #971 
Use `semver` package to reliably compare semantic versions.
Previously, using the trick `major * 100 + minor * 10 + patch`, which will suffer incorrect behavior if the comparing between, for example, `1.11.0` and `0.43.0`.
> fix(semver): use semver util to check version upgrades

- package.json
- tsconfig.json
- yarn.lock
Related to #1039 (production optimization started there)
Also closes #1072 
Use `importHelpers` to tell TS to import helper code (i.e. needed for backwards compatibility or downleveling) from `tslib`. This helps reducing the web asset size by eliminating duplicate code.
> For certain downleveling operations, TypeScript uses some helper code for operations like extending class, spreading arrays or objects, and async operations. By default, these helpers are inserted into files which use them. This can result in code duplication if the same helper is used in many different modules.
References: …
> build(ts): eliminate duplicate helper code

- .github/workflows/ci.yaml
- locales/en/common.json
- package.json
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisFilters.tsx
- src/app/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisScoreFilter.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Recordings/RecordingFilters.tsx
- src/app/Settings/Language.tsx
- src/app/Settings/SettingsUtils.ts
- src/app/Shared/Redux/Configurations/DashboardConfigSlice.tsx
- src/app/Shared/Redux/Configurations/TopologyConfigSlice.tsx
- src/app/Shared/Redux/Filters/AutomatedAnalysisFilterSlice.tsx
- src/app/Shared/Redux/Filters/RecordingFilterSlice.tsx
- src/app/Shared/Redux/ReduxStore.tsx
- src/app/Shared/Redux/utils.ts
- src/app/Topology/Shared/utils.tsx
- src/test/Common.tsx
- src/test/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.test.tsx
- src/test/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisScoreFilter.test.tsx
- src/test/Dashboard/Charts/mbean/__snapshots__/MBeanMetricsChartCard.test.tsx.snap
- src/test/DateTimePicker/DateTimePicker.test.tsx
- src/test/DateTimePicker/MeridiemPicker.test.tsx
- src/test/DateTimePicker/TimePicker.test.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Recordings/RecordingFilters.test.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/Shared/Services/Login.service.test.tsx
- tsconfig.json
Related to #689 
Added Typescript type-checking to ensure correct typings. Also, run this type checking in CI on pull request.
As for Mirage JS, I kept the type as `any` to represent unknown shapes of parsed objects returned from API server.
Help catch mismatched types when defining interfaces, types and creating object. This helps avoiding potential bugs (i.e. a field missing or extra fields are added).
> chore(ts): fix typescript type-checking errors

- locales/en/public.json
Fixes: #1030 
This change is more user friendly. Renaming the title from `WebSocket Connection Debounce` to `WebSocket Retry Interval` makes it more understandable for all users.
Pointed out by @andrewazores  to improve UX as name and description should be understandable by a typical user without having to reach for a manual page or search engine
2. *...*
> fix(web): rename connection debounce to connection retry interval

- .github/workflows/pr-ci.yml
> feat(ci): /build_test PR command 

- .github/workflows/ci-preview.yml
Related to #1045 
This extends workflow to run on release branches.
> I think we'll want to have a CI setup and deployment for the latest release branch, cryostat-v2.4 in this case in anticipation of the next release which will also contain these Mirage changes, so that the upstream website can just link to or iframe a preview of the latest upstream release, rather than development snapshots
Deployment: https://tthvo-cryostat-web-cryostat-v24.surge.sh
Action: https://github.com/tthvo/cryostat-web/actions/runs/5182474577/jobs/9339300166
> feat(ci): allow preview deployment on release branches

- src/app/Topology/GraphView/CustomNode.tsx
Fixes: #1114
This updates the Topology view to render Cryostat icons for Cryostat Agent targets, and as before, OpenJDK's Duke for JMX targets.
The original note I made about dark vs. light mode and the reverse icon is ignored here because the Topology view only changes its background field colour to suit the theme, but the app icon being changed here is always presented on top of a white background.
This helps users to differentiate what kind of target node they are looking at without having to click on each to pull up the details pane and check the connection URL.
2. Go to …
> feat(topology): render Cryostat icon for Agent targets

- README.md
Related to #221 
Update CI badge to point to Github Action view.
Previously, the badge holds the link the badge itself, not the Github Action view.
> docs(read-me): correct ci status badge

- .github/workflows/submodule.yaml
Fixes: #916 
This change will sign all commits on `git submodule update`
All commits should be verified.
2. *...*
> build(ci): submodule should sign commits

- .github/workflows/ci.yaml
- TESTING.md
Related #1038
This change allows contributors to get a better understanding of the integration testing framework.
> docs(itest): add supplemental integration testing documentation

- .github/workflows/submodule.yaml
Related to #1113 
Remove bot user git configurations to allow the signed commits to be verified.
https://github.com/cryostatio/cryostat-web/pull/1113#issuecomment-1738896699
> ci(submodule): remove bot user git configurations

- src/app/Shared/Services/Api.service.tsx
- src/app/utils/utils.ts
Fixes: #993
Depends on https://github.com/cryostatio/cryostat/pull/1692
Depends on https://github.com/cryostatio/cryostat/issues/1738
> chore(recordings): remove subdirectory for jvmId in recording requests

- src/app/Agent/AgentLiveProbes.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/api.types.ts
- src/mirage/index.ts
- src/test/Agent/AgentLiveProbes.test.tsx
- src/test/RecordingMetadata/BulkEditLabels.test.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Depends on https://github.com/cryostatio/cryostat/pull/1689
Related to https://github.com/cryostatio/cryostat/issues/1452
> chore(recordings): check target's jvmId for recording events

- src/app/Topology/Entity/utils.tsx
Related to: https://github.com/cryostatio/cryostat/issues/1452
Related to: #1126
> chore(topology): check for jvmId in notifications from Cryostat

- locales/en/public.json
Related to: https://github.com/cryostatio/cryostat/issues/1695
> chore(strings): update 2.4 user-facing strings

- .github/workflows/ci.yaml
- .github/workflows/dependent-issues.yml
- .github/workflows/image-cleanup.yml
- .github/workflows/labeler.yml
- .github/workflows/linked-issue.yml
- .github/workflows/pr-ci.yml
- .github/workflows/pr-labeled.yml
- .github/workflows/release-drafter.yml
- .github/workflows/semantic-pr.yml
Fixes: #1172 
Related to: [#1783](https://github.com/cryostatio/cryostat/issues/1783)
2. *...*
> chore(ci): request necessary permissions

- src/app/Shared/Services/Login.service.tsx
- src/index.html
- src/mirage/index.ts
- src/test/Shared/Services/Login.service.test.tsx
- webpack.common.js
Fixes https://github.com/cryostatio/cryostat/issues/1810
Sets up the `index.html` to use a `<base href="./">`, which indicates to the user's browser that all of the other assets referenced by the index should be resolved relative to the location where the browser found the index on the server.
In the usual case where the Cryostat server responds to requests like `GET /` with `index.html`, the browser will see the associated resources like `favicon.ico` and look for it with a `GET /favicon.ico`. Likewise, the web-client JavaScript resolves API requests assuming that the paths start from the server root location, ex. …
> fix(requests): use relative request paths

- .github/workflows/submodule.yaml
> ci(submodule): remove config for updating old 2.x repo

- src/app/Shared/Services/Api.service.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Related to cryostatio/cryostat3#2
Depends on https://github.com/cryostatio/cryostat3/pull/235
Removes the old API V2.1 JWT download flow in favour of simply following the new API V3 download URL redirect flow.
This restores the web UI's ability to download active and archived recording files with the new V3 API, which does not re-implement the previous JWT flow.
See  https://github.com/cryostatio/cryostat3/pull/235
> feat(recording): API v3 downloads

- src/app/Rules/RulesUploadModal.tsx
Fixes: https://github.com/cryostatio/cryostat3/issues/261
> fix(rules): remove id key from uploaded rule

- src/app/Shared/Services/Api.service.tsx
Fixes: #1120
Depends on: https://github.com/cryostatio/cryostat3/pull/260
> fix(notifications): parse detail for notification body

- src/app/Shared/Services/Api.service.tsx
Related to https://github.com/cryostatio/cryostat3/pull/290
Depends on https://github.com/cryostatio/cryostat3/pull/290
Removes the old API v2.1 auth token download flow in the middle of the event template download action. In 3.0 the client can simply request the file.
This enables the "Events -> Event Templates -> SomeTemplate -> Download" feature to work again with 3.0.
2. *...*
> chore(templates): remove auth token download flow

- src/app/Shared/Services/Api.service.tsx
Related to #65
Related to #410
Related to https://github.com/cryostatio/cryostat3/issues/11
GraphQL queries which do not explicitly suppress notifications will emit a graphical notification box if there are GraphQL errors in the response.
Previously, notifications would only be displayed if the GraphQL response status code was `4xx/5xx`. With this change, `2xx` responses which contain a GraphQL error response will also display notifications. This provides the user (or developer) more information about what went wrong with the request.
2. *...*
> fix(graphql): emit notifications on server error response

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
Based on #1219
Depends on https://github.com/cryostatio/cryostat3/pull/312
With this change, the following views should work as expected again:
1. Recordings > Archived
2. Archives > All Targets
3. Archives > All Archives (already working before this PR)
4. Archives > Uploads, but this also requires https://github.com/cryostatio/cryostat3/pull/314
> fix(archives): adjust queries and response handling for updated data schema

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/types.ts
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/api.types.ts
- src/app/Topology/Actions/utils.tsx
- src/app/utils/fakeData.ts
- src/mirage/index.ts
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
- src/test/CreateRecording/CustomRecordingForm.test.tsx
- src/test/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.test.tsx
- src/test/RecordingMetadata/BulkEditLabels.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Based on #1222
Depends on https://github.com/cryostatio/cryostat3/pull/315
Adjustments for updated GraphQL schema in Cryostat 3.0.
This re-enables the Topology view and all its features.
2. *...*
> fix(topology): update for new GraphQL schema

- src/app/Shared/Services/Login.service.tsx
Related to https://github.com/cryostatio/cryostat3/issues/365
Removes unused code that was left in "just in case". In https://github.com/cryostatio/cryostat3/pull/366 and https://github.com/cryostatio/cryostat-helm/pull/131 I have determined that it really is not needed anymore due to the new authproxy architecture.
> chore(oauth): remove unused openshift-specific logout function

- src/app/Archives/AllArchivedRecordingsTable.tsx
- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/api.types.ts
- src/test/Archives/AllArchivedRecordingsTable.test.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
- src/test/RecordingMetadata/BulkEditLabels.test.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Related to: #1222
[mentioned here](https://github.com/cryostatio/cryostat-web/pull/1222#issuecomment-2053303242)
1. checkout PR
2. run `yarn test:ci` All tests should pass.
> fix(test): fix broken test related to GraphQL

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Topology/Entity/EntityDetails.tsx
Fixes: #1244
Depends on https://github.com/cryostatio/cryostat3/pull/342 (`targetIds` filter is added here)
Updates GraphQL queries that act upon particular targets to do so by their IDs, rather than using the `connectUrl` as the node name filter.
It is not guaranteed, and is not true for Cryostat Agent instances, that the discovery nodes' names are equal to their connection URLs. This fixes queries being unable to locate such nodes.
1. Combine with https://github.com/cryostatio/cryostat3/pull/342
2. Select `quarkus-test-agent` target
3. Go to Recordings, create a new recording, wait a few moments, then archive it
4. Click the …
> fix(graphql): query target nodes by targets' IDs rather than connectUrls

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Topology/Entity/EntityDetails.tsx
See https://github.com/cryostatio/cryostat3/issues/389
Based on #1245
Adds handling of potentially null/undefined GraphQL API response fields.
GraphQL responses may contain null/undefined fields when execution errors occurred. Notification popups appear to inform the user of these errors, but the views invoking these API calls should not render an overall broken error view state. It's better to render what content was available from the response, if any, rather than an overall broken view when only some subset of the data may not be available.
2. *...*
> fix(graphql): handle nullable response fields that can occur when there are server errors

- src/app/Topology/Actions/types.ts
- src/app/Topology/Actions/utils.tsx
Fixes: #1251 
- Update the `allowList` and `blockList` to be more flexible based on the tree element.
- Added check for `REALM` annotation to ensure that only Custom Target is allowed to be deleted.
See #1251
> fix(topology): delete action should be available for custom targets

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
Fixes: [437](https://github.com/cryostatio/cryostat3/issues/437)
mentioned by @andrewazores on [https://github.com/cryostatio/cryostat3/issues/437](https://github.com/cryostatio/cryostat3/issues/437)
2. Archive a recording and go  to `Archives -> All Targets` and try to expand the table row corresponding to the related target. You should be able to see the `archived recordings`.
> fix(GraphQL): fix VallidationError: null ID for non-null `BigInteger!`

- src/app/Topology/Actions/CreateTarget.tsx
- **fix(custom-targets): handle case where response does not include data or reason fields**
- **fix(custom-targets): lock form Create button until successful test**
Fixes: #1261
- handles the case where the response body does not have `.data.reason` fields. This can happen if the server encounters an unexpected error and responds with an HTTP 500, in which case the response format is not a Cryostat API V2 format but a standard Quarkus 500 format.
- locks the Custom Target creation form Create button until a successful connection test is performed. If the form is updated (URL or credentials) the button is re-locked.
When creating a …
> fix(custom-targets): lock form Create button until successful test

- src/app/Shared/Services/Login.service.tsx
- src/mirage/index.ts
- src/test/Shared/Services/Login.service.test.tsx
Fixes https://github.com/cryostatio/cryostat3/issues/489
Related to https://github.com/cryostatio/cryostat3/pull/490
If the response from the server includes the `Gap-Auth` header, use that to determine the user's logged in username. If not, fall back to using the `POST /api/v2.1/auth` response body. If anything is blank or fails then use the empty string, which the UI already renders as the anonymous user icon.
1. Check out cryostat3 and build with this PR
2. `./smoketest.bash -O`
3. Verify that the username `user` appears on the top bar
4. Restart smoketest as `./smoketest.bash -Op` to disable the auth proxy
5. Verify that the …
> fix(auth): render username in top bar

- src/app/QuickStarts/quickstarts/automated-rules-quickstart.tsx
- src/app/QuickStarts/quickstarts/dashboard-quickstart.tsx
- src/app/QuickStarts/quickstarts/generic-quickstart.tsx
- src/app/QuickStarts/quickstarts/settings-quickstart.tsx
- src/app/QuickStarts/quickstarts/start-a-recording.tsx
- src/app/QuickStarts/quickstarts/topology/custom-target-quickstart.tsx
- src/app/QuickStarts/quickstarts/topology/group-start-recordings.tsx
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- **fix(quickstart): rename WebSocket Connection Debouce -> WebSocket retry interval**
- **remove explicit versioning, quickstarts correspond to whichever release they are developed with and embedded into**
- **remove mention of "View Report" action from recording quickstart**
- **remove mention of credentials storage location**
- **add note about client-side feature flags**
Fixes: #1265
Fixes: #1266
Fixes: #1267
1. *Run CRYOSTAT_IMAGE=quay.io... sh …
> fix(quickstarts): remove outdated feature descriptions

- src/app/Shared/Components/MatchExpression/MatchExpressionHint.tsx
Related to https://github.com/cryostatio/cryostat3/issues/511
Adds a check that the annotation exists before reading it to compare its value.
In the old JavaScript-based expression evaluation, indexing the map with a nonexistent key would simply result in an `undefined` value which would compare as `false` against the test value. In CEL it is a runtime error to index with a nonexistent key, so there should be an existence check before the access and comparison to ensure that the result comes back as a successful evaluation with a `false` result, rather than as an error.
1. Check out cryostat3 with this PR and build
2. …
> fix(matchexpr): tooltip hint checks for annotation existence before asserting value

- src/app/Shared/Components/MatchExpression/MatchExpressionVisualizer.tsx
- src/app/Shared/Services/api.types.ts
- src/app/Topology/Shared/utils.tsx
Fixes: #1277
The root of the bug is that the object passed in to the entity details view is the Target object itself, whereas it should be the Discovery TargetNode which contains the Target as a property.
2. *...*
> fix(matchexpr): fix bug in evaluator List view

- src/mirage/index.ts
- webpack.prod.js
Fixes: #1271
1. Check out PR
2. `yarn start:dev:preview` should bring up the preview/demo UI. There should be a Fake Target, with a Demo template. Topology view should work, dashboard should work, recording start/stop/archive/delete should work, expanding recording for automated analysis should work. GraphQL-powered things will not work, snapshot recording creation does not work.
3. `yarn run build:preview:notests && cd dist && python3 -m http.server`, then open `http://localhost:8000` in a browser. The preview should work just the same as in the step above.
> test(mirage): correct server authority string in preview builds

- .github/workflows/pr-ci.yml
Fixes: #1288 
Install podman 4 and start Podman API for building container images. We can remove podman-4 installation when `ubuntu-24.04` is out of beta.
See #1288
> ci(tools): use podman for building container images

- .github/workflows/pr-ci.yml
Related to #1290 
- Emulate docker with podman before image build. 
#1290 didn't exactly solved the problem. `docker` was stilled used for building images.
> ci(tools): emulate docker with podman before image builds

- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/cryostat-dashboard-templates.tsx
Fixes: #1297 
- Corrected chart source url construct for jft-metrics charts.
- Fix `Recording Start Time` metric chart kind. Previously, throwing `Invalid Value` error (due to mismatched kind name).
See #1297
> fix(dashboard): correct chart source url for jfr-metrics charts

- README.md
- src/app/Shared/Services/Report.service.tsx
- webpack.dev.js
Fixes: https://github.com/cryostatio/cryostat/issues/328
Related to https://github.com/cryostatio/cryostat/pull/327
- Configure dev-server to proxy API requests to Cryostat and Grafana.
This should allow development of web without having to rebuild the container image all the time. I think this is a bit simpler than handling CORS.
This idea comes from the fact that Grafana proxies its client's requests to jfr-datasource so I guess dev-server can do the same. What do you think @andrewazores?
https://webpack.js.org/configuration/dev-server/#devserverproxy
> feat(dev-server): configure request proxy for dev-server

- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
- src/app/Rules/CreateRule.tsx
- src/app/TargetView/TargetContextSelector.tsx
Related to #1110
See #1303
1. Fixes up functionality so targets can be selected
2. Uses the item "description" field to display the connect URL, instead of placing it in parentheses
3. Adds a "Clear selection" button, related to https://github.com/cryostatio/cryostat-web/issues/883
~~Card resize functionality on the dashboard is broken, so visiting the dashboard with a selected target breaks the UI. Go directly to `/recordings` via URL to sidestep this issue. You can "Clear selection" before going back to the Dashboard, if necessary.~~
Turns out this was a one-liner fix, so I included it here.
> chore(pf5): upgrade TargetContextSelector

- src/app/AppLayout/AppLayout.tsx
- src/app/Settings/Config/FeatureLevels.tsx
Related to #1303
Fixes up the styling of the settings cog, help menu, and user menu on the masthead, as well as the Quick Starts item under the help menu.
> fix(masthead): correct styling of masthead icons and quickstart menu item

- src/app/Recordings/ActiveRecordingsTable.tsx
Related to #1313 
Correctly use `recording.maxSize` to render. Previously, `recording.maxAge` was mistakenly used.
Recording's max size should be displayed correctly. Only affected `main` and `pf5` (i.e. after #1313).
> fix(recordings): maxSize should be displayed correctly

- src/app/RecordingMetadata/utils.ts
- src/test/RecordingMetadata/RecordingLabelFields.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
Fixes #1322 
Fixed the incorrect label parsing utility. The labels should be rendered correctly now.
See #1322
> fix(labels): fix broken label file parsing in archive upload modal

- locales/en/common.json
- locales/en/public.json
- src/app/CreateRecording/CreateRecording.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/CreateRecording/SnapshotRecordingForm.tsx
- src/app/DateTimePicker/DateTimePicker.tsx
- src/app/DateTimePicker/TimePicker.tsx
- src/app/DateTimePicker/TimezonePicker.tsx
- src/app/DurationPicker/DurationPicker.tsx
- src/app/RecordingMetadata/BulkEditLabels.tsx
- src/app/RecordingMetadata/ClickableLabel.tsx
- src/app/RecordingMetadata/LabelCell.tsx
- src/app/RecordingMetadata/RecordingLabelFields.tsx
- src/app/RecordingMetadata/utils.ts
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Recordings/ArchivedRecordingsTable.tsx
- src/app/Recordings/Filters/DurationFilter.tsx
- src/app/Recordings/Filters/LabelFilter.tsx
- src/app/Recordings/Filters/NameFilter.tsx
- src/app/Recordings/Filters/RecordingStateFilter.tsx
- src/app/Recordings/RecordingActions.tsx
- src/app/Recordings/RecordingFilters.tsx
- src/app/Recordings/RecordingLabelsPanel.tsx
- src/app/Recordings/RecordingsTable.tsx
- src/app/Settings/Config/DatetimeControl.tsx
- src/app/Shared/Components/SelectTemplateSelectorForm.tsx
- src/app/app.css
- src/test/DateTimePicker/TimezonePicker.test.tsx
Other upgrading the components to be compatible with PF5. Here some major and minor revamps.
| Changes | Description | Screenshot |
|--------------|-------------------|------------------|
| New label editor for bulk editting | Label editor is now following PF5 [guideline](https://www.patternfly.org/components/label/react-demos/) and closer to that of [OpenShift](http://openshift.github.io/openshift-origin-design/designs/administrator/4.0/labels/). The user can define labels with `key=value`.  The same editor is used for Recording Form and Archive Upload. | …
> chore(pf5): upgrade Recording view to Patternfly 5

- package.json
- src/app/Recordings/ActiveRecordingsTable.tsx
- src/app/Rules/Rules.tsx
- src/app/utils/utils.ts
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- yarn.lock
Fixes https://github.com/cryostatio/cryostat-web/issues/1328
Related to https://github.com/cryostatio/cryostat-web/issues/625
Uses existing `formatBytes` function on the Automated Rules table to improve the display of the Maximum Size column.
Adds the `humanize-duration` dependency and adds a `formatDuration` function to improve the display of durations in Automated Rules and Active Recordings tables.
Rearranges Rules columns to read more nicely.
See https://github.com/cryostatio/cryostat-web/issues/1328
1. Build with PR
2. Create Automated Rule with expression matching some target(s), with an archival period, max size, and max age …
> feat(units): improve display of bytes and duration units

- src/app/Archives/AllTargetsArchivedRecordingsTable.tsx
- src/app/Archives/Archives.tsx
- src/app/Archives/utils.tsx
- src/app/CreateRecording/CustomRecordingForm.tsx
- src/app/Shared/Services/api.types.ts
- src/app/Shared/Services/api.utils.ts
- src/app/Topology/Actions/CreateTarget.tsx
- src/app/Topology/GraphView/CustomNode.tsx
- src/app/utils/fakeData.ts
- src/mirage/factories.ts
- src/test/Agent/AgentLiveProbes.test.tsx
- src/test/Archives/AllTargetsArchivedRecordingsTable.test.tsx
- src/test/CreateRecording/CustomRecordingForm.test.tsx
- src/test/CreateRecording/SnapshotRecordingForm.test.tsx
- src/test/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.test.tsx
- src/test/Dashboard/AutomatedAnalysis/AutomatedAnalysisConfigForm.test.tsx
- src/test/Dashboard/Charts/jfr/JFRMetricsChartCard.test.tsx
- src/test/Dashboard/Charts/mbean/MBeanMetricsChartCard.test.tsx
- src/test/Dashboard/Dashboard.test.tsx
- src/test/Events/EventTemplates.test.tsx
- src/test/Events/EventTypes.test.tsx
- src/test/RecordingMetadata/BulkEditLabels.test.tsx
- src/test/RecordingMetadata/LabelCell.test.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
- src/test/Recordings/ArchivedRecordingsTable.test.tsx
- src/test/Recordings/RecordingFilters.test.tsx
- src/test/Recordings/Recordings.test.tsx
- src/test/Rules/CreateRule.test.tsx
- src/test/TargetView/TargetSelect.test.tsx
Related to https://github.com/cryostatio/cryostat-web/issues/1320
See https://github.com/cryostatio/cryostat/pull/598
2. *...*
> chore(discovery): use target.agent field for determining connection type

- locales/en/public.json
- src/app/About/AboutDescription.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/api.types.ts
- src/app/build.json
Related to cryostatio/cryostat#550
Depends on https://github.com/cryostatio/cryostat/pull/589
2. *...*
> feat(about): link to commit hash

- locales/en/public.json
- src/app/AppLayout/ThemeToggle.tsx
- src/app/Topology/Actions/WarningResolver.tsx
- src/app/Topology/Entity/EntityDetails.tsx
- src/app/Topology/GraphView/TopologyControlBar.tsx
- src/app/Topology/GraphView/TopologyGraphView.tsx
- src/app/Topology/GraphView/utils.tsx
- src/app/Topology/Toolbar/TopologyFilters.tsx
- src/app/Topology/Topology.tsx
Graph Layout was previously failing due to `undefined` Controller (i.e. via `getController` func). My speculation is that as new `Model` (i.e. on discovery tree refresh)  is set on the controller, old graph elements are still animating, thus causing the issue. The combination of the following changes seem to fix:
- Debounce (100ms)  discovery tree refresh when new target events are emitted. Optional but nice to have.
- Destroy graph layout before setting new model.
| Changes | Description | Screenshot |
|--------------|-------------------|------------------|
| Reset view should expand all collapsed groups | A quick …
> fix(topology): fix Cola layout failing due to pending outdated graph elements

- locales/en/common.json
- locales/en/public.json
- src/app/AppLayout/AppLayout.tsx
- src/app/AppLayout/LogoutIcon.tsx
- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCard.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisCardList.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisConfigDrawer.tsx
- src/app/Dashboard/AutomatedAnalysis/AutomatedAnalysisFilters.tsx
- src/app/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisNameFilter.tsx
- src/app/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisTopicFilter.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx
- src/app/Dashboard/DashboardCardActionMenu.tsx
- src/app/Dashboard/DashboardLayoutCreateModal.tsx
- src/app/Dashboard/DashboardLayoutToolbar.tsx
- src/app/Dashboard/LayoutTemplateGroup.tsx
- src/app/Dashboard/LayoutTemplatePicker.tsx
- src/app/Dashboard/SearchAutocomplete.tsx
- src/app/Dashboard/cryostat-dashboard-templates.tsx
- src/app/Dashboard/types.ts
- src/app/QuickStarts/QuickStartDrawer.tsx
- src/app/app.css
- src/app/index.tsx
- stylePaths.js
- webpack.dev.js
- webpack.prod.js
- Upgrade Dashboard view to Patternfly 5.
- Upgraded QuickStart to Patternfly 5
- Only need to add missing imported css module for quickstart package.
- Still there is a small bug with TIP admonition styling.
- Moved common css style paths to a JS module to avoid having to change both places in webpack configs.
- Updated Grafana dashboard panel's id. I organized the enum in order of increasing id (top down), similar to what being displayed on Grafana.
| Changes | Description | Screenshot |
|--------------|-------------------|------------------|
| Newly organized toolbar for Automatic Analysis Card | Filter items …
> chore(pf5): upgrade Dashboard view to Patternfly 5

- locales/en/public.json
- src/app/NotFound/NotFound.tsx
- src/app/NotFound/NotFoundCard.tsx
Related to #1303
Upgraded 404 page to Patternfly 5. Looks like the styling from EmptyState is also centering the texts.
> chore(pf5): upgrade 404 page to Patternfly 5

- src/app/Recordings/Filters/DatetimeFilter.tsx
- src/app/Recordings/Filters/DurationFilter.tsx
- src/mirage/index.ts
Related to #1303 #1315 
- Updated Mirage API mocks to include git commit hash.
- Fixed Mirage `/api/v2/targets` API route to consider `dryrun` query parameter.
- Fixed some remaining type-check issues.
Previously, About page is throwing error in preview mode.
> fix(about): add missing buildInfo in mocked health response

- src/app/Dashboard/AddCard.tsx
- src/app/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisNameFilter.tsx
- src/app/Dashboard/AutomatedAnalysis/Filters/AutomatedAnalysisTopicFilter.tsx
- src/app/Dashboard/DashboardCardActionMenu.tsx
- src/app/Dashboard/DashboardLayoutToolbar.tsx
- src/app/Dashboard/LayoutTemplateGroup.tsx
- src/app/DateTimePicker/TimezonePicker.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Recordings/Filters/DatetimeFilter.tsx
- src/app/Recordings/Filters/DurationFilter.tsx
- src/app/Rules/Rules.tsx
- src/app/Settings/Config/DatetimeControl.tsx
- src/app/Shared/Components/ScrollableMenuContent.tsx
- src/app/TargetView/TargetContextSelector.tsx
- src/app/TargetView/TargetSelect.tsx
- src/app/Topology/Actions/NodeActions.tsx
- src/app/Topology/Actions/types.ts
- src/app/Topology/Actions/utils.tsx
- src/app/Topology/Toolbar/HelpButton.tsx
- src/app/Topology/styles/base.css
- Set `maxMenuHeight` and `isScrollable` where applicable.
- Menu-related changes:
- Added a workaround to allow the menu footer to be sticky.
- Updated the footer's action button styles to use 'secondary' and 'link'. Follow this guideline: https://www.patternfly.org/components/button/design-guidelines#link-button
- For `Delete` action, use "danger" style, following this guideline: https://www.patternfly.org/components/menus/menu/design-guidelines#red-text-menu
Previously, in order to view the action buttons at the menu footer, the user has to scroll all the way down. With these changes, the footer is always …
> fix(pf5): allow menu footer to be sticky and use danger style for delete/clear buttons

- src/app/Topology/Toolbar/TopologyFilters.tsx
Related to #1339 
Fixed the topology filter menu list to include only unique options. The `new Set` should be called on the array of strings before transforming to `ReactNode`.
| Previous | Now |
|:--:|:--:|
| ![image](https://github.com/user-attachments/assets/058042ce-3ee8-4279-8142-5744b15abb0a) | ![image](https://github.com/user-attachments/assets/1d4f0c5a-34be-4fdf-a904-a366ac7fd036)|
> fix(topology): filter options should show unique value only

- src/app/SecurityPanel/Credentials/StoredCredentials.tsx
Added an additional API fetch to obtain the up-to-date number of matched targets for a credential since the notification message always returns 0.
There is a small side effect: there is a gap between the time when the notification message is received and the table is updated. I think this is still better than the potential confusion when the number of matched targets is 0 (when it should not be).
See https://github.com/cryostatio/cryostat-web/pull/1303#issuecomment-2349295493
> fix(credentials): number of matched targets should be updated corretly on notification

- src/app/Topology/Actions/CreateTarget.tsx
Updated the css class to use prefix `pf-v5-` such that the correct color is applied. This was missed during upgrades.
| Before | After |
|:---:|:---:|
| ![image](https://github.com/user-attachments/assets/14daeb42-a4b6-438e-a638-cdbd72a3c24a) | ![image](https://github.com/user-attachments/assets/7aae94d0-e6c5-420b-a475-41d57d6884bb) |
|  ![image](https://github.com/user-attachments/assets/cb82b05f-9454-4b51-a67d-970fd7e04011) | ![image](https://github.com/user-attachments/assets/0ea16a14-4364-4d27-93fe-b31d829e7f1a)|
> fix(custom-target): validation icons should have correct color

- package.json
- src/app/build.json
> chore(release): set versions for 3.0.1

- package.json
- yarn.lock
This reverts commit b8393e44ebf6adc90160eb96faa9e20a2c0cfcef.
Reverts #1404
2. *...*
> build(deps-dev): downgrade ts-jest from 29.2.5 to 27.1.5

- src/app/Events/EventTemplates.tsx
- src/app/Events/Events.tsx
- src/app/Rules/CreateRule.tsx
- src/app/Shared/Services/Api.service.tsx
- src/test/Rules/CreateRule.test.tsx
Related to https://github.com/cryostatio/cryostat-web/issues/225
1. Allows the Event Templates view to be displayed even when there is no target selected. This allows the user to view, add, or remove Custom Event Templates without needing to select a target - particularly useful when there aren't any targets currently discovered.
2. Similarly, the Agent Probe Templates view is displayed when there is no target selected.
3. Fixes a similar bug on the Automated Rule creation form where the event template selections were limited to the set intersection of those available on the matched targets. If there were no matched targets …
> feat(eventtemplates): enable custom event template UI to display when no target is selected

- locales/en/public.json
- src/test/Events/__snapshots__/EventTypes.test.tsx.snap
> fix(eventtypes): remove duplicate word in search placeholder

- src/app/SecurityPanel/Credentials/StoredCredentials.tsx
Fixes: https://github.com/cryostatio/cryostat/issues/756
When a `CredentialsStored` notification is emitted, use the contents of that notification to patch the client-side model of the stored Credentials objects. The original returned value from the API response [does not contain](https://github.com/cryostatio/cryostat/blob/443c9c09ec8dd819476b661eb8a384d64d3cbefb/src/main/java/io/cryostat/credentials/Credentials.java#L157) the real value, so this workaround keeps the UI in sync and avoids a `t.targets is undefined` error.
1. See …
> fix(storedcredentials): define target match array to avoid undefined reference error

- src/app/AppLayout/AppLayout.tsx
- src/app/AppLayout/SslErrorModal.tsx
- src/app/CreateRecording/CreateRecording.tsx
- src/app/Dashboard/Charts/jfr/JFRMetricsChartCard.tsx
- src/app/Dashboard/Dashboard.tsx
- src/app/Dashboard/DashboardSolo.tsx
- src/app/Events/EventTemplates.tsx
- src/app/Rules/CreateRule.tsx
- src/app/Topology/Actions/CreateTarget.tsx
- src/app/Topology/Actions/quicksearches/custom-target.tsx
- src/app/Topology/Actions/utils.tsx
- src/app/routes.tsx
- src/app/utils/utils.ts
- src/test/utils.tsx
- webpack.dev.js
- webpack.prod.js
Fixes: #1533 
This PR allows for setting a basepath using an environment variable, that gets prepended to routes in cryostat-web.
This allows for creating custom paths, useful when nesting cryostat-web inside another application that already uses paths that would conflict with cryostat-web. For example, the OpenShift Console has its own Topology page at `/topology`, so being able to set a basepath of 'cryostat' would allow for `/cryostat/topology` to route to cryostat-web without conflicting with existing content.
> feat(routes): allow setting a basepath via an environment variable

- src/app/Recordings/ActiveRecordingsTable.tsx
- src/test/Recordings/ActiveRecordingsTable.test.tsx
Fixes: [#1286](https://github.com/cryostatio/cryostat-web/issues/1286)
This changes the activeRecordingsTable notification handling logic to call refreshRecordingsList when receiving creation/deletion notifications rather than updating with only the fields in the notification. This ensures that the state of the table remains accurate.
When the query in the linked issue is run a second time it results in the notifications being fired in the following order:
Recording Created
Recording Deleted
Pre-patch the table would see the recording deleted notification last and remove it from the table despite the recording still being present in the target. Calling refreshRecordingsList and getting the state of the target's recordings from the API shows the same.
1. Run Cryostat via smoketest or …
> fix(recordings): Fix active recordings table refresh behavior for replace:"ALWAYS"

- src/app/AppLayout/AppLayout.tsx
- src/app/BreadcrumbPage/BreadcrumbPage.tsx
- src/app/NotFound/NotFoundCard.tsx
- src/app/Rules/Rules.tsx
- src/app/Shared/Components/CryostatLink.tsx
- src/app/Topology/Actions/QuickSearchPanel.tsx
- src/app/Topology/Shared/Components/TopologyEmptyState.tsx
This is a follow-up to: https://github.com/cryostatio/cryostat-web/pull/1534
The PR listed above made changes to allow setting a base path for routes, but missed instances of `<Link>`, so this PR adds the `toPath()` to those elements.
Fixes routing using `<Link>` elements when using a custom base path.
> fix(routing): fix Link routing when using custom basepath

- src/app/Shared/Services/api.utils.ts
Fixes an incorrect notification message for recording archiving failures.
Related to cryostatio/cryostat#761
1. Run cryostat via ./mvnw quarkus:dev
2. Fail to archive a recording
3. Observe the notification emitted.
> fix(notifications): Fix notification message for Recording Archive failures

- src/app/AppLayout/AppLayout.tsx
- src/app/AppLayout/AuthModal.tsx
- src/app/BreadcrumbPage/BreadcrumbPage.tsx
- src/app/NotFound/NotFound.tsx
- src/app/Shared/Components/CryostatLink.tsx
- src/app/TargetView/TargetContextSelector.tsx
- src/app/Topology/Shared/utils.tsx
Updates the TargetContextSelector and NotFound components to use the CryostatLink intsead of Link, to properly route when using a basepath.
Updates the CryostatLink to optionally handle onClick, so it can be used in a couple more areas.
Fixes the breadcrumb links to just simply use <Link>, because the incoming routes already have a basepath prepended they do not have to use <CryostatLink> (it's added twice).
Clicking around the console plugin I ran into a 404 on the TargetContextSelector because it was routing to '/topology/create-custom-target' instead of '/cryostat/topology/create-custom-target'. This PR updates that usage, as …
> fix(links): fix Breadcrumb links and improve CryostatLink

- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/NotificationChannel.service.tsx
See #1544
When the request already contains query parameters, for example when originating from the Archives view where a `?tab=foo` query parameter is used for routing to the specific tabbed subview, the previous logic would incorrectly build a query string like `?tab=foo?ns=namespace&name=cryostat`. Note the doubled-up `?`.
> fix(notifications): correctly append query parameters

- src/app/Shared/Services/Api.service.tsx
See #1544 #1542
Fixes https://github.com/cryostatio/cryostat-web/issues/1549
Similar to the other recent "contextual" changes in support of the OpenShift Console Plugin.
We use a common client-side JavaScript trick to trigger the browser to download files - we create a virtual `<a href="/path/to/download" />` element and trigger a simulated click on it. This way the browser's native file download facilities handle the download, including whatever download stream management may apply etc. This is generally better than trying to use `XMLHttpRequest` or `fetch` APIs directly, since those would require us to use `blob` types and …
> fix(download): use contextual URL mapping for file downloads

- src/app/Shared/Services/Report.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/utils/fakeData.ts
Fixes #1551 
Currently have this in draft while I wait for my container build to finish so I can test it with the console plugin in crc. At the moment cryostat-web looks okay in dev preview (both by itself and through a local console).
This PR updates the `reportJson()` to use the url and headers from CryostatContext when requesting the automated analysis.
Without the url and headers the console plugin is unable to make the proper request in order to request the json.
> chore(reports): use CryostatContext url and headers for reportJson

- src/app/AppLayout/AppLayout.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Login.service.tsx
- src/app/Shared/Services/Services.tsx
- src/app/Shared/Services/Targets.service.tsx
- src/test/Shared/Services/Login.service.test.tsx
Related to cryostatio/cryostat-openshift-console-plugin#3
2. *...*
> fix(services): perform lazy initialization

- src/app/Archives/Archives.tsx
Fixes: https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/102
Adds keys to the Tab components generated for the Archives page.
Without the keys, an error is thrown in the console plugin when running a local console frontend: `Cannot read property 'setExtraStackFrame' of undefined`.
> fix(archives): add keys to Archive tabs to prevent setExtraStackFrame error

- src/app/Shared/Services/Api.service.tsx
Fixes: https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/107
Fixes up logic where request headers could get overwritten instead of correctly merged.
See https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/107
2. *...*
> fix(api): merge contextual headers

- src/app/Recordings/RecordingActions.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/Shared/Services/Capabilities.tsx
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/110
2. *...*
> fix(grafana): Grafana dashboard uses contextual path and parameters and capability to override URL

- src/app/Topology/GraphView/TopologyGraphView.tsx
Fixes: [#122
](https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/122)
This change switches the boolean in `visualization.fromModel()` in TopologyGraphView from false to true, in-order to "merge" the topology elements on update instead of removing and rebuilding them.
What seems to be the issue is that when the boolean is false the visualization clears out all the old elements before re-creating them. This results in the error because it ends up setting the controller to undefined, but during the process of destroying the colalayout there is a check for that controller.
With merge set to true the old elements are …
> fix(topology): merge topology elements on update

- src/app/Dashboard/Diagnostics/DiagnosticsCard.tsx
Removes the beta label from the diagnostics card, related to https://github.com/cryostatio/cryostat-web/pull/1563
> chore(diagnostics): Remove beta label from diagnostics card labels

- src/app/Shared/Components/CryostatLink.tsx
- src/app/Topology/Entity/EntityDetails.tsx
Fixes: [#144](https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/144)
The links in the Topology EntityDetails were not using CryostatLink, so any basepath was not being prepended to the pathname.
However, those links make use of To from LinkProps, which CryostatLink did not previously handle.
CryostatLink now handles incoming paths that are of types string | partial<path>.
Fixes the links on the Topology page.
> fix(links): update CryostatLink to handle partial paths

- locales/en/public.json
> fix(locale): correct improperly escaped character

- src/app/About/AboutDescription.tsx
- src/test/About/AboutDescription.test.tsx
> fix(about): allow alternate build suffix separator characters

- src/app/Settings/Settings.tsx
- src/test/Settings/Settings.test.tsx
Fixes: #1640
I ran into a bug where when working on a development level setting it was still displaying if my target level was production. It had to do with FeatureLevel.DEVELOPMENT being 0 which is a falsy value, which caused the production level number to be used instead.
Will allow development settings to be restricted to the development feature level.
> fix(settings): fix feature level assignment

- src/app/Shared/Services/Api.service.tsx
Related to https://github.com/cryostatio/cryostat/pull/927
Noticed a bug when attempting to upload an agent probe template. The POST is incorrect and includes the filename both as a path parameter and a body form field. The backend only expects the form field.
> fix(probetemplate): correct POST request

- src/app/Shared/Services/Api.service.tsx
Fixes https://github.com/cryostatio/cryostat/issues/942
See cryostatio/cryostat#888
Related to #1620
When updating (`PATCH`ing) an Automated Rule, #1620 would send the update like:
```json
{
"name": "my_rule",
"metadata": {
"labels": [
{
"key": "foo",
"value": "bar"
}
]
}
}
```
(ie the `KeyValue[]` type used for serialization purposes).
However, the backend actually expects it in the following format, which matches what the backend also accepts when creating a new rule via `POST`:
```json
{
"name": "my_rule",
"metadata": {
"labels": {
"foo": "bar"
}
}
}
```
> fix(rules): patch Automated Rules with expected body format

- src/test/DateTimePicker/TimezonePicker.test.tsx
Fixes: #1666
Wait for the timezone label to be hidden before continuing on in the test.
There is a test failure that can happen if the label doesn't disappear by the time the `expect` assertions start to run.
1. Run `yarn run test -- TimezonePicker` on main a handful of times, it's likely you'll hit a test failure
2. Check out this PR and verify the test failure doesn't occur
> test(tz): fix sporadic TimezonePicker test failure

- src/app/SecurityPanel/ImportCertificate.tsx
- src/app/Shared/Services/Api.service.tsx
- src/app/TargetView/TargetContextSelector.tsx
- src/app/TargetView/TargetDetailsModal.tsx
- src/app/Topology/styles/base.css
- **correct iteration over target object annotations**
- **feat(target-selector): add info button to summon target details modal**
- **render trusted certificates as LabelGroup to handle large list overflow**
Fixes: #976
1. render the list of additional imported SSL/TLS certificates under Security as a `LabelGroup` and `Labels` rather than a plain `List`. This is a little more modern-looking, but it is also more compact and takes up less screen space for what is not usually critical information.
2. fixes a bug that prevented the Match Expression Visualizer (see Automated Rules or Stored Credentials, the Graph icon) from listing …
> feat(target-selector): add info button to summon target details modal
