cryostatio/cryostat-web

src/app/recording-list/archived/archived-recording-list.component.ts, src/app/recording-list/current/current-recording-list.component.html, src/app/recording-list/current/current-recording-list.component.ts, src/app/recording-list/recording-list.component.ts
Add "View in Grafana" button to current recordings tab results, not only archived
=> Current recording upload

src/app/connect/connect-button.component.html, src/app/connect/connect-button.component.ts
Disable autoconnection for solo targets
=> Expect scan-targets response to contain connectUrl and alias

src/app/recording-list/current/current-recording-list.component.ts
Related to https://github.com/rh-jmc-team/container-jfr/issues/53
=> Display notification with "save" command result

src/app/connect/connect-button.component.ts
=> Specify port number in connect command only if nonzero

src/app/api.service.ts, src/app/recording-list/archived/archived-recording-list.component.ts
- recording upload function moved into the api service
- included authorization token header
Closes #25
=> Include auth header in recording upload request

src/app/recording-list/archived/archived-recording-list.component.html
Place refresh button at rightmost position to match active recording tab
toolbar layout
=> Switch archived recording tab toolbar button order

src/app/command-channel.service.ts
=> Send auth token as subprotocol

src/app/command-channel.service.ts
=> Base64-encode WebSocket SubProtocol tokens

src/app/api.service.ts, src/app/app.component.ts, src/app/command-channel.service.ts
Use X-WWW-Authenticate response header sent by container-jfr on POST
/auth request to determine Basic or Bearer auth scheme, and display an
authorization prompt to the user according to this scheme. Also adjust
API and Command Channel auth protocols for the detected scheme.
Fixes #38
=> Detect auth scheme and display auth prompt accordingly

src/app/create-recording/custom-recording/custom-recording.component.html, src/app/create-recording/custom-recording/custom-recording.component.ts
=> Allow finer-grained specification of recording duration

src/app/Login/BasicAuthForm.tsx, src/app/Login/BearerAuthForm.tsx, src/app/Login/FormProps.tsx, src/app/Login/Login.tsx
Basic login form asks for separate username and password, Bearer form
asks for just auth token
Additionally, use Card styling
Before:
After:
=> Split Login component into React Form components

src/app/AppLayout/AppLayout.tsx, src/index.html
Remove the unused "Toolbar" from the page header and set the HTML page title attributes to match ContainerJFR
=> Clean up Patternfly Seed remnants

src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/CommandChannel.service.tsx
Related to rh-jmc-team/container-jfr#148
=> Prefix request paths with /api/v1

src/app/AppLayout/AppLayout.tsx, src/app/BreadcrumbPage/BreadcrumbPage.tsx, src/app/CreateRecording/CreateRecording.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/CreateRecording/SnapshotRecordingForm.tsx, src/app/Dashboard/Dashboard.tsx, src/app/Events/EventTemplates.tsx, src/app/Events/EventTypes.tsx, src/app/Events/Events.tsx, src/app/Login/BasicAuthForm.tsx, src/app/Login/BearerAuthForm.tsx, src/app/Login/FormProps.tsx, src/app/Login/Login.tsx, src/app/Notifications/NotificationCenter.tsx, src/app/Notifications/Notifications.tsx, src/app/RecordingList/ActiveRecordingsList.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/RecordingList/RecordingList.tsx, src/app/RecordingList/RecordingsDataTable.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/CommandChannel.service.tsx, src/app/Shared/Services/Services.tsx, src/app/TargetSelect/TargetSelect.tsx, src/app/TargetView/TargetView.tsx, src/app/routes.tsx
See #71 - this re-applies the same fixes but rebased on the latest master. This was done from scratch rather than slogging through a rebase, but the end results are similar.
=> Fix linting issues

src/app/RecordingList/ActiveRecordingsList.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/CommandChannel.service.tsx
Rebased and reopened version of #75 after `react` branch was merged into `master`
~~Based on top of #84~~
=> View in Grafana

package.json, src/app/RecordingList/ActiveRecordingsList.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/RecordingList/RecordingList.tsx, src/app/RecordingList/ReportFrame.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/Report.service.tsx, src/app/Shared/Services/Services.tsx
Rebased and reopened version of #73 after `react` branch was merged into `master`
=> Expandable recording rows for inline reports

src/app/TargetSelect/TargetSelect.tsx
See #90. Reopening after default branch rename.
Fixes #89
=> Include target connection port number, if any

src/app/CreateRecording/CreateRecording.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/Events/EventTemplates.tsx, src/app/Events/Events.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/Services.tsx
Fixes #36
See also:
- rh-jmc-team/container-jfr#199
- rh-jmc-team/container-jfr-core#40
=> Custom templates

src/app/Events/EventTemplates.tsx
=> remove download option for "ALL" template

src/app/RecordingList/ArchiveUploadModal.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/Shared/Services/Api.service.tsx
=> Implement archive re-upload

src/app/CreateRecording/CreateRecording.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/Shared/Services/Api.service.tsx
=> Interface for advanced recording options 

src/app/Shared/Services/Api.service.tsx
Related to rh-jmc-team/container-jfr#270
=> Use status code 427 instead of 407

src/app/RecordingList/ActiveRecordingsList.tsx
=> Display recording options for current recording list

src/app/TargetSelect/TargetSelect.tsx
=> Prevent refresh when same target is reselected

src/app/AppLayout/AuthModal.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/Events/EventTemplates.tsx, src/app/Events/EventTypes.tsx, src/app/RecordingList/ActiveRecordingsList.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/Services.tsx, src/app/Shared/Services/Target.service.tsx, src/app/TargetSelect/TargetSelect.tsx, src/app/TargetView/TargetView.tsx
=> Display alias for selected target in widget (refactor TargetService)

src/app/ErrorView/ErrorView.tsx, src/app/Events/EventTemplates.tsx, src/app/Events/EventTypes.tsx, src/app/Loading/Loading.tsx, src/app/LoadingView/LoadingView.tsx, src/app/RecordingList/RecordingsDataTable.tsx
=> Extract error and loading state to single implementation

src/app/SecurityPanel/CertificateUploadModal.tsx, src/app/SecurityPanel/SecurityPanel.tsx, src/app/Shared/Services/Api.service.tsx, src/app/routes.tsx
Fixes #135 
Would the message regarding the restart required need to be different depending on the platform? I am not sure what would be the best way to indicate this.
Also, I am not sure if the way I check if the file type is compatible is exhaustive or the best way to do so.
=> UI to upload SSL Certificates

src/app/Shared/Services/Api.service.tsx
I missed this and it had broke the UI.
=> Fix issue from certificate upload changes

src/app/AppLayout/AppLayout.tsx, src/app/AppLayout/SslErrorModal.tsx, src/app/ErrorView/ErrorView.tsx, src/app/Shared/Services/Api.service.tsx
=> When connection fails due to SSL, show link to upload cert

src/app/RecordingList/ActiveRecordingsList.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/RecordingList/ReportFrame.tsx, src/app/Shared/Services/Report.service.tsx, src/app/Shared/Services/Services.tsx
See also: rh-jmc-team/container-jfr#318
=> Improve client-side report caching and error handling

src/app/CreateRecording/CustomRecordingForm.tsx, src/app/DurationPicker/DurationPicker.tsx, src/app/Events/EventTemplates.tsx, src/app/RecordingList/ActiveRecordingsList.tsx, src/app/RecordingList/ArchivedRecordingsList.tsx, src/app/Settings/Settings.tsx, src/app/Shared/Services/Settings.service.tsx, src/app/TargetSelect/TargetSelect.tsx, src/app/routes.tsx
=> Configurable auto-refresh

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .github/workflows/semantic-pr.yml, .mergify.yml
Apply configurations from cryostatio/cryostat#550, cryostatio/cryostat#549, cryostatio/cryostat#553
=> ci(config): apply CI actions configs

src/app/Shared/Services/NotificationChannel.service.tsx
See cryostatio/cryostat#590 for reasoning/context.
=> fix(notifications): trip auth on startup

src/app/AppLayout/AppLayout.tsx, src/app/Notifications/NotificationCenter.tsx, src/app/Notifications/Notifications.tsx, src/app/Shared/Services/Api.service.tsx
=> feat(notifications): implement notifications drawer

src/app/Shared/Services/Report.service.tsx
=> fix(reports): cache to sessionStorage

src/app/Events/EventTemplates.tsx
=> fix(events): reset event template search filter when switching targets

src/app/Events/EventTypes.tsx
=> fix(events): reset event type search filter when switching targets

src/app/Events/EventTemplates.tsx, src/app/Events/EventTypes.tsx, src/app/RecordingList/ActiveRecordingsList.tsx
=> fix(targets): backport bugfixes when switching targets

src/app/AppLayout/AppLayout.tsx
Clean backport of #271
* feat(about): version string is clickable link to browse sources
* feat(about): add File a Report bug link
* fix(about): use Text component with _blank target
=> feat(about): enhance version string and bug tracker (#271)

src/app/Shared/Services/NotificationChannel.service.tsx
=> chore(notifications): convert notification categories to CamelCase

src/app/AppLayout/AppLayout.tsx
=> fix(about): short hash may not be 9 chars

src/app/Shared/Services/NotificationChannel.service.tsx
=> fix(notifications): Fix notifications url request failure handling

src/app/Notifications/Notifications.tsx
=> fix(notifications): Sort notifications into exactly one category

src/app/Settings/Settings.tsx, src/app/Shared/Services/Login.service.tsx, src/app/Shared/Services/Services.tsx, src/app/Shared/Services/Settings.service.tsx
=> fix(websocket): fix repeated disconnect/reconnect spin

src/app/Login/Login.tsx, src/app/Login/OpenShiftPlaceholderAuthForm.tsx, src/app/Shared/Services/Login.service.tsx
Related https://github.com/cryostatio/cryostat/issues/717
This PR redirects users to the OpenShift Container Platform login page and authenticates users with the resulting access token. A follow-up PR is needed to implement the logout feature.
=> feat(auth): Add OAuth redirect authentication

src/app/Recordings/ActiveRecordingsTable.tsx
=> fix(recordings): Ensure ActiveRecordingsTable properly refreshes recordings list

src/app/AppLayout/AppLayout.tsx
=> fix(notifications): Show newest unread notification first

src/app/Recordings/ArchivedRecordingsTable.tsx
=> fix(reports): Delete cached report upon archived recording deletion

src/app/Shared/Services/NotificationChannel.service.tsx
=> fix(notifications): Show stopped recording notification

src/app/CreateRecording/CustomRecordingForm.tsx, src/app/Recordings/ActiveRecordingsTable.tsx, src/app/Recordings/ArchivedRecordingsTable.tsx, src/app/Recordings/RecordingActions.tsx, src/app/Recordings/ReportFrame.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/NotificationChannel.service.tsx, src/app/Shared/Services/Report.service.tsx
=> fix(archivedrecordings): use notifications to update state without query

src/app/Notifications/Notifications.tsx, src/app/Shared/Services/Api.service.tsx
Fix a bug where missing jfr-datasource or Grafana dashboard URL configuration caused Cryostat version number to not be populated
Fixes #365
=> fix(health): handle version separate from Grafana config

src/app/Events/EventTemplates.tsx
=> feat(templates): use notifications to update state without query

src/app/Shared/Services/Api.service.tsx
Related to cryostatio/cryostat#826
Related to cryostatio/cryostat#827
Related to cryostatio/cryostat#828
=> chore(api): use API endpoints promoted from beta to v2.1

src/app/Shared/Services/Api.service.tsx
Use new health "configured" status fields to determine if other
services components are expected to be available, in addition to the
existing "available" status fields indicating actual reachability for
configured components
Fixes #384
An easy way to test this and the associated backend fix is to use the backend devserver setup or smoketest script, and modify them to vary between a) datasource env var set and container started within pod, b) datasource env var set but container not started, c) datasource env var not set. This can be repeated for the dashboard alone or in conjunction. If both are configured and can be reached over the network then no notification should be displayed. If either are configured by env var but cannot be reached then the red error notification will be …
=> fix(health): process health configured/available results

src/app/SecurityPanel/StoreJmxCredentials.tsx
=> fix(jmx): populate credentials table via notification only (#404)

src/app/NotFound/NotFound.tsx, src/app/app.css
=> fix(notfound): Update 404 page with missing routes

src/app/Recordings/ArchivedRecordingsTable.tsx
Fixes #420 by checking if notifications apply to the selected target when viewing the Archived Recordings table on the Recordings tab.
Related to #397
Related to #368 
Related to #344
=> fix(archives): Only display archives for selected target

src/app/Recordings/ActiveRecordingsTable.tsx, src/app/Recordings/ArchivedRecordingsTable.tsx
=> fix(recordings): uncheck deleted recordings

src/app/Recordings/ActiveRecordingsTable.tsx, src/app/Recordings/ArchivedRecordingsTable.tsx
Fixes #437 
The problem with the previous fix was that `handleRowCheck` correctly removes the index of the deleted recording from the `checkedIndices` list, but  the indices of the remaining recordings after the deleted row still needed to be decremented by 1. The `checkedIndices` were also modified twice for the web client that manually deleted the recording and received the deletion notification.
This fix will use the index of the deleted recording to update `checkedIndices` only when a deletion notification is received. If an unrelated web client selected recordings, those `checkedIndices` should be preserved to avoid re-selecting recordings every time a recording gets deleted.
This PR is affected by https://github.com/cryostatio/cryostat-web/issues/430 - you can test the archived …
=> fix(recordings): disable actions after deleting all recordings

yarn.lock
Related to #452
See https://github.com/cryostatio/cryostat-web/pull/453#issuecomment-1152470895
=> ci(yarn): use registry.yarnpkg.com

src/app/TargetSelect/TargetSelect.tsx, src/test/Rules/CreateRule.test.tsx, src/test/Rules/__snapshots__/CreateRule.test.tsx.snap, src/test/Targets/TargetSelect.test.tsx, src/test/Targets/__snapshots__/TargetSelect.test.tsx.snap
Fixes #494
Will add new tests for TargetSelect in this PR.
=> feat(targets): added count of discovered targets to TargetSelect dropdown widget

src/app/CreateRecording/CustomRecordingForm.tsx
Fixes #500 
Labels should be added to newly created recording.
=> fix(recordings): labels should be applied to created recordings

src/app/Shared/Services/Api.service.tsx, src/app/utils/utils.ts
Fixes #505 
A metadata file as `${recordingName}.metadata.json` is also downloaded if a recording is downloaded.
=> feat(metadata): downloading recordings also download associated metadata

.github/workflows/dependent-issues.yml, .github/workflows/linked-issue.yml, .github/workflows/pr-labeled.yml
Configs copy-pasted from the main Cryostat repo.
=> ci(github): copy linked and dependent issues workflows

src/app/Shared/Services/Api.service.tsx
Fixes #517 
Depends on https://github.com/cryostatio/cryostat/pull/1066
=> feat(graphql): add aggregate information for active recordings in the GraphQL API

src/app/Archives/Archives.tsx, src/app/Recordings/ArchivedRecordingsTable.tsx, src/app/Recordings/RecordingActions.tsx, src/app/Shared/Services/Api.service.tsx, src/test/Recordings/ArchivedRecordingsTable.test.tsx
Fixes #445 
Related https://github.com/cryostatio/cryostat/pull/1047
=> fix(archives): use target-specific archive API endpoints

src/app/Modal/DeleteWarningUtils.tsx, src/app/TargetSelect/CreateTargetModal.tsx, src/app/TargetSelect/TargetSelect.tsx, src/test/Targets/TargetSelect.test.tsx
Fixes #492 
Deleting a custom target now shows a deletion modal if enabled.
=> feat(target): show warning prompt when deleting custom targets

.github/workflows/ci.yaml
Related to cryostatio/cryostat#1118
=> ci(tests): don't run tests twice

src/app/CreateRecording/CustomRecordingForm.tsx
Fixes #568 
Removed the nested Form component in recording creation form.
References: https://github.com/facebook/react/issues/12318#issuecomment-369908609
=> fix(recordings): remove nested forms

src/app/Archives/AllArchivedRecordingsTable.tsx, src/test/Archives/AllArchivedRecordingsTable.test.tsx
Fixes #575 
This will eventually not matter because of https://github.com/cryostatio/cryostat-web/issues/552 but it makes sense to fix this for the 2.2.0 release.
=> fix(archives): add ArchivedRecordingCreated notification hook to refresh All Archives view

.github/CODEOWNERS, .github/dependabot.yml
Fixes #617 
Added Dependabot set up.
=> chore(deps-bot): set up Dependabot

package.json, yarn.lock
Closes https://github.com/cryostatio/cryostat-web/pull/654
=> build(deps): remove unused @types/victory

.github/workflows/image-cleanup.yml, .github/workflows/pr-ci.yml, .mergify.yml
Fixes: #714
This change adds the ability to test a front-end UI change without checking out the branch. 
1. Haven't add mergify to auto label `safe-to-test` yet.
2. Haven't added workflow to cleanup ghcr images.
Will do that a bit later.
This change is helpful because it is easier for devs to test like this rather than checking out a new branch, building, and then having to prune branches later.
1. Can't really manually test this without pushing.
2. However, it has been tested on my fork here: https://github.com/maxcao13/cryostat-web/pull/6
3. Look at logs of actions here:  https://github.com/maxcao13/cryostat-web/actions/runs/3662156149/jobs/6191051609
=> feat(ci): add PR test images

src/app/Archives/Archives.tsx, src/app/Recordings/ActiveRecordingsTable.tsx, src/app/Recordings/ArchivedRecordingsTable.tsx
Fixes: #809 
Fixes #810 
Fixes #585 
See original issues for comments.
=> fix(recordings): fix recording table displays

src/app/Topology/Shared/Entity/EntityDetails.tsx, src/app/Topology/Shared/Entity/utils.tsx
=> fix(topology): fix resource update in entity detail view

src/app/Dashboard/AddCard.tsx, src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx, src/app/Dashboard/DashboardLayoutCreateModal.tsx, src/app/Dashboard/DashboardLayoutToolbar.tsx, src/app/Dashboard/LayoutTemplateGroup.tsx, src/app/Dashboard/LayoutTemplatePicker.tsx, src/app/Dashboard/LayoutTemplateUploadModal.tsx, src/app/Dashboard/dashboard-utils.tsx, src/app/Joyride/CryostatJoyride.tsx, src/app/QuickStarts/quickstarts/dashboard-quickstart.tsx, src/app/Shared/FileUploads.tsx, src/app/Shared/Services/Report.service.tsx, src/app/app.css
Related #922
List of changes:
* Provides a warning to the user when an uploaded layout template is of `BETA` feature level
* Gives a better error message to users when an AA card is constructed to create the recording
* Don't tell users in dashboard quickstart to delete layout
* Remove joyride debug mode
* Fix bug where layout template in suggested are scrolled to or are selected if duplicate template exists in other categories
* Remove animation on drawer open and close for layout template picker
* Remove placeholder select options in card creation wizard
* Fix lowercase colorTheme placeholder in MBeanMetrics card
=> fix(dashboard): various dashboard related fixes

src/app/Topology/Shared/Entity/utils.tsx
Related to: #962 
This sets up auto-refresh for entity detail table (i.e. node decorator for active recording is also auto-refresh) if enabled. The structure is a little different from what we usually do for other views.
Sorry, another place to add auto-refresh. See #962.
Enable auto refresh and watch the resources updates (for examples, see the network inspector).
=> feat(topology): entity resource should auto refresh if enabled

.mergify.yml, package.json
Related to https://github.com/cryostatio/cryostat/issues/1459
That `version` field is actually used unless we publish our source code on an npm registry. It's just there to be consistent :))
=> build(config): update package.json and mergify for 2.3 release

src/app/build.json
Related to https://github.com/cryostatio/cryostat/issues/1459
Update asset version to `2.3.0` for 2.3 release.
=> chore(build.json): update asset version to 2.3

README.md, license-config.json, src/app/AppLayout/AppLayout.tsx, src/app/Dashboard/AddCard.tsx, src/app/QuickStarts/QuickStartDrawer.tsx, src/app/QuickStarts/README.md, src/app/QuickStarts/quickstart-utils.tsx, src/app/QuickStarts/quickstarts/automated-rules-quickstart.tsx, src/app/QuickStarts/quickstarts/cryostat-link-quickstart.tsx, src/app/QuickStarts/quickstarts/dashboard-quickstart.tsx, src/app/QuickStarts/quickstarts/generic-quickstart.tsx, src/app/QuickStarts/quickstarts/settings-quickstart.tsx, src/app/QuickStarts/quickstarts/start-a-recording.tsx, src/app/Rules/CreateRule.tsx, src/app/Settings/AutoRefresh.tsx, src/test/Settings/__snapshots__/AutoRefresh.test.tsx.snap
Fixes: #969
Depends on #971
This change adds some documentation and guidelines for how to write Cryostat quick starts. The word and styling should be similar to OpenShift quickstarts and so the README directs readers to read upon the OpenShift documentation.
Also fixes some a11y issues with the Navigation bar NavList containing elements non list elements, and the Settings cog + Add Card buttons that has no discernable text or label.
See #969
=> docs(quickstart): add quick start README for writing and style guidelines + update current quick starts aligning with those guidelines

src/app/AppLayout/AuthModal.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/Dashboard/AddCard.tsx, src/app/Dashboard/Charts/mbean/MBeanMetricsChartCard.tsx, src/app/Dashboard/ErrorCard.tsx, src/app/Dashboard/cryostat-dashboard-templates.tsx, src/app/Dashboard/dashboard-utils.tsx, src/app/Shared/Redux/Configurations/DashboardConfigSlice.tsx
Fixes: #1005
The change adds a display mapping function to the prop configs for SelectOptions such that the text strings can be transformed and the values for the props do not have to be the same as the ones to display to the user.
=> fix(dashboard): add display mapper function to dashboard card prop configurations

locales/en/public.json, src/app/Agent/AgentLiveProbes.tsx, src/app/Agent/AgentProbeTemplates.tsx, src/app/CreateRecording/CustomRecordingForm.tsx, src/app/ErrorView/ErrorView.tsx, src/app/Login/ConnectionError.tsx, src/app/Login/OpenShiftPlaceholderAuthForm.tsx, src/app/Modal/DeleteWarningUtils.tsx, src/app/RecordingMetadata/RecordingLabelFields.tsx, src/app/Rules/CreateRule.tsx, src/app/SecurityPanel/Credentials/CreateCredentialModal.tsx, src/app/Settings/Settings.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/Report.service.tsx, src/app/Topology/Actions/CreateTarget.tsx, src/app/Topology/Shared/TopologyExceedLimitState.tsx, src/test/CreateRecording/CustomRecordingForm.test.tsx, src/test/CreateRecording/SnapshotRecordingForm.test.tsx, src/test/CreateRecording/__snapshots__/CustomRecordingForm.test.tsx.snap, src/test/Events/EventTemplates.test.tsx, src/test/Events/EventTypes.test.tsx, src/test/RecordingMetadata/RecordingLabelFields.test.tsx, src/test/RecordingMetadata/__snapshots__/RecordingLabelFields.test.tsx.snap, src/test/Recordings/ActiveRecordingsTable.test.tsx, src/test/Rules/CreateRule.test.tsx
Fixes: #1013
Fixes: #589
Fixes some error/warning/exceptions strings in the -web repo.
=> chore(strings): string fixes for 2.3

.github/workflows/ci-preview.yml
Related to #1045 
Allow manual trigger for preview CI.
Useful when we need a rebuild without changes source files.
Push to fork and go to Action tab.
=> feat(ci): enable manual trigger of preview CI

README.md, TESTING.md
Related to #1045 
Related to #1039 
Patch README with updated dependency requirements and steps.
=> docs(README): update README

src/app/Agent/AgentProbeTemplates.tsx, src/test/Agent/AgentProbeTemplates.test.tsx
Depends on https://github.com/cryostatio/cryostat/pull/1563
Related to https://github.com/cryostatio/cryostat-core/issues/239
Update to use correct field from notifications.
=> chore(agent): use consistent notification field

src/app/build.json
=> chore(about): link to full license file

src/app/RecordingMetadata/BulkEditLabels.tsx
=> fix(graphql): correct query name

.mergify.yml, package.json, src/app/build.json
Related to cryostatio/cryostat#1695
=> chore(release): bump versions for 2.4.0 release

package.json, src/app/build.json
Related to cryostatio/cryostat#1695
=> chore(release): set versions for 2.4.0 release

src/app/SecurityPanel/CertificateUploadModal.tsx, src/app/SecurityPanel/Credentials/StoreCredentials.tsx, src/app/SecurityPanel/ImportCertificate.tsx, src/app/SecurityPanel/SecurityPanel.tsx, src/app/SecurityPanel/types.ts, src/app/Shared/Components/FileUploads.tsx, src/app/Shared/Components/JmxAuthDescription.tsx, src/app/Shared/Components/JmxSslDescription.tsx, src/app/Shared/Components/types.ts, src/app/Topology/Entity/EntityDetails.tsx, src/app/Topology/Shared/utils.tsx, src/test/Agent/AgentProbeTemplates.test.tsx, src/test/Events/EventTemplates.test.tsx, src/test/Recordings/ArchivedRecordingsTable.test.tsx, src/test/Rules/Rules.test.tsx
Related to cryostatio/cryostat#1695
Updates some user strings and UI elements following docs feedback
=> feat(jvmid): enhance UI hints when JVM ID cannot be generated

src/app/SecurityPanel/Credentials/StoreCredentials.tsx, src/app/Shared/Components/JmxAuthDescription.tsx
Related to https://github.com/cryostatio/cryostat-web/pull/1119
=> chore(credentials): clean up UI text

.github/workflows/submodule.yaml
Fixes: https://github.com/cryostatio/cryostat3/issues/125
2. *...*
=> feat(ci): should commit and push changes to src/main/webui

package.json, src/app/build.json
Related to https://github.com/cryostatio/cryostat/issues/1695
=> chore(build): set versions for 2.4.0 release

package.json, src/app/About/AboutDescription.tsx, src/app/build.json
- chore(about): clean up for 3.0.0 development
- fixup! chore(about): clean up for 3.0.0 development
- fixup! chore(about): clean up for 3.0.0 development
2. *...*
=> chore(about): set up links and version parsing for 3.0

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/pr-ci.yml
=> ci(pr): build cryostat3 for preview

.github/workflows/pr-ci.yml
=> ci(pr): fix image tagging workflow

.github/workflows/pr-ci.yml
=> pr(ci): print docker images on build completion

.github/workflows/pr-ci.yml
=> ci(pr): pull built image from docker into podman

.github/workflows/pr-ci.yml
=> ci(pr): update test image comment

.github/workflows/pr-ci.yml
Related to cryostatio/cryostat-core#92
=> ci(core): use -core from Central, do not rebuild locally

src/app/Agent/AgentLiveProbes.tsx, src/test/Agent/AgentLiveProbes.test.tsx
Fixes: #1247
Depends on https://github.com/cryostatio/cryostat3/pull/401
2. *...*
=> fix(jmcagent): correct notification handling

.mergify.yml, package.json, src/app/build.json
Related to https://github.com/cryostatio/cryostat3/issues/469
2. *...*
=> chore(release): set versions to 4.0.0-dev

.github/ISSUE_TEMPLATE/config.yml, .github/workflows/ci.yaml, .github/workflows/pr-ci.yml, .github/workflows/submodule.yaml
Related to: https://github.com/cryostatio/cryostat/issues/469
=> chore(rename): replace all cryostat3 references to cryostat

.github/workflows/ci.yaml
Related to https://github.com/cryostatio/cryostat-web/pull/1303
See https://github.com/cryostatio/cryostat-web/pull/1304#discussion_r1692095228
2. *...*
=> ci(pr): enable PR for upstream feature branches

src/app/Shared/Redux/Filters/TopologyFilterSlice.tsx, src/app/Topology/Shared/utils.tsx, src/app/Topology/Toolbar/TopologyFilters.tsx
=> feat(topology): add target.Agent topology filter 

.github/workflows/ci-preview.yml, .github/workflows/ci.yaml
=> ci(node): use single latest Node LTS version

README.md
=> docs(readme): update NodeJS version requirement

package.json, src/app/build.json
=> chore(release): set versions for 3.0.2-dev

src/test/Events/__snapshots__/EventTemplates.test.tsx.snap
=> test(tables): fixup for react-table version bump

.github/workflows/pr-ci.yml
See https://github.com/cryostatio/cryostat-core/pull/494
2. *...*
=> ci(criu): add CRIU PPA for Podman dependency

.github/workflows/pr-ci.yml
=> ci(cryostat): upgrade builder to JDK 21

.github/workflows/pr-ci.yml
=> ci(jdk): distribution typo

src/app/About/AboutDescription.tsx, src/test/About/AboutDescription.test.tsx, src/test/About/__snapshots__/AboutDescription.test.tsx.snap
=> fix(about): be more lenient about build version format

src/app/AppLayout/AppLayout.tsx, src/app/Shared/Services/Api.service.tsx, src/app/Shared/Services/Login.service.tsx, src/app/Shared/Services/Services.tsx, src/app/Shared/Services/api.types.ts, src/app/utils/fakeData.ts, src/test/Shared/Services/Login.service.test.tsx
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/issues/3
2. *...*
=> feat(context): allow contextual override for API requests

src/app/Archives/Archives.tsx, src/app/Events/EventTemplates.tsx, src/app/Rules/Rules.tsx, src/app/Shared/Services/Capabilities.tsx, src/app/index.tsx
Related to cryostatio/cryostat-openshift-console-plugin#3
Related to https://github.com/cryostatio/cryostat-openshift-console-plugin/pull/90
Adds an additional context and provider near the top of the component hierarchy, with a default value of `{ fileUploads: true }` indicating that the existing file uploading features should remain enabled. No functional differences should be observed when interacting with Cryostat Web as a standalone UI.
The console plugin can override this with `{ fileUploads: false }` with its own context at its own component hierarchy root. This allows conditional UI elements to be hidden (or never added) …
=> feat(capabilities): functionality to disable UI capabilities for different contexts

package.json, src/app/build.json
=> chore(release): set version to 4.1.0-dev

src/app/Dashboard/Diagnostics/DiagnosticsCard.tsx
Fixes https://github.com/cryostatio/cryostat-web/issues/1562 , moves the diagnostics card up to Production level
=> chore(diagnostics): Promote diagnostics card to Production level

.github/workflows/pr-ci.yml
See #1672
PR bot comment is out of date - the Cryostat smoketest script uses HTTPS by default and has for quite some time.
=> ci(pr): update bot comment

tsconfig.json
=> chore(tsconfig): increase target to es6

tsconfig.json
Fixes: #1757
Related to #1733 (iteration over object annotations)
This reverts commit 4747a971c15b8b3d22d6bc47a6d86f5e5ec3d4bb (#1731).
2. *...*
=> chore(tsconfig): decrease target to es5

src/app/TargetView/TargetContextSelector.tsx
=> fix(targetselect): disable button if no target selected

src/app/Dashboard/Diagnostics/DiagnosticsCard.tsx, src/app/routes.tsx
=> feat(diagnostics): promote Diagnostics to production feature level
